### ISSUE TITLE
Buffer.writeAll from a Source doesn't work while Buffer.readAll to a Sink works

### ISSUE THREAD

**Issue by yrezgui** [square/okio#1092]
Hi all,
I'm building a [filesystem API for Android](https://github.com/google/modernstorage) using Okio and I'm seeing a weird behavior in my tests that I can't seem to explain.

You can see [here](https://github.com/google/modernstorage/blob/11990f4d70ebe3466f6778fe51f193f9d4dd55c2/storage/src/androidTest/java/com/google/modernstorage/storage/SharedMediaStoreTest.kt#L55) that I'm writing in a `Sink` from a `Source` :

```kotlin
fileSystem.sink(path).buffer().writeAll(appContext.assets.open("sample.$extension").source())
```

If you run this test file, all of them succeed except the text file:
<img width="571" alt="image" src="https://user-images.githubusercontent.com/1113976/152145479-7c8d525d-3034-4e3c-9249-2aa01695b285.png">

Here's the error stack trace:

```
02-02 12:28:41.287 19653 19675 I TestRunner: started: addText(com.google.modernstorage.storage.SharedMediaStoreTest)
02-02 12:28:41.288 19653 19675 I GrantPermissionCallable: Permission: android.permission.READ_EXTERNAL_STORAGE is already granted!
02-02 12:28:41.288 19653 19675 I GrantPermissionCallable: Permission: android.permission.WRITE_EXTERNAL_STORAGE is already granted!
02-02 12:28:41.288 19653 19675 I GrantPermissionCallable: Permission: android.permission.READ_EXTERNAL_STORAGE is already granted!
02-02 12:28:41.290  5305 22921 W MediaProvider: Ignoring mutation of  _data from com.google.modernstorage.storage.test
02-02 12:28:41.291  5305 22921 W MediaProvider: isAppCloneUserPair failed. Users: 0 and 0
02-02 12:28:41.291  5305 22921 W MediaProvider: isAppCloneUserPair for user 0: false
02-02 12:28:41.297  5305 22921 D MediaProvider: Open with FUSE. FilePath: /storage/emulated/0/Download/added-1643801321289.txt. Uid: 10241. Media Capabilities Uid: 0. ShouldRedact: false. ShouldTranscode: false
02-02 12:28:41.316 19653 19682 D MediaScannerConnection: Scanned /storage/emulated/0/Download/added-1643801321289.txt to content://media/external_primary/file/111
02-02 12:28:41.325  5305 22921 D MediaProvider: Open with FUSE. FilePath: /storage/emulated/0/Download/added-1643801321289.txt. Uid: 10241. Media Capabilities Uid: 0. ShouldRedact: false. ShouldTranscode: false
02-02 12:28:41.327 19653 19675 E TestRunner: failed: addText(com.google.modernstorage.storage.SharedMediaStoreTest)
02-02 12:28:41.327 19653 19675 E TestRunner: ----- begin exception -----
02-02 12:28:41.328 19653 19675 E TestRunner: java.io.EOFException
02-02 12:28:41.328 19653 19675 E TestRunner: 	at okio.RealBufferedSource.require(RealBufferedSource.kt:199)
02-02 12:28:41.328 19653 19675 E TestRunner: 	at okio.RealBufferedSource.readByte(RealBufferedSource.kt:209)
02-02 12:28:41.328 19653 19675 E TestRunner: 	at com.google.modernstorage.storage.SharedMediaStoreTest.addFile(SharedMediaStoreTest.kt:72)
02-02 12:28:41.328 19653 19675 E TestRunner: 	at com.google.modernstorage.storage.SharedMediaStoreTest.addText(SharedMediaStoreTest.kt:109)
02-02 12:28:41.328 19653 19675 E TestRunner: 	at java.lang.reflect.Method.invoke(Native Method)
02-02 12:28:41.328 19653 19675 E TestRunner: 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
02-02 12:28:41.328 19653 19675 E TestRunner: 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
02-02 12:28:41.328 19653 19675 E TestRunner: 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
02-02 12:28:41.328 19653 19675 E TestRunner: 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
02-02 12:28:41.328 19653 19675 E TestRunner: 	at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
02-02 12:28:41.328 19653 19675 E TestRunner: 	at androidx.test.rule.GrantPermissionRule$RequestPermissionStatement.evaluate(GrantPermissionRule.java:134)
02-02 12:28:41.328 19653 19675 E TestRunner: 	at androidx.test.rule.GrantPermissionRule$RequestPermissionStatement.evaluate(GrantPermissionRule.java:134)
02-02 12:28:41.328 19653 19675 E TestRunner: 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
02-02 12:28:41.328 19653 19675 E TestRunner: 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
02-02 12:28:41.328 19653 19675 E TestRunner: 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
02-02 12:28:41.328 19653 19675 E TestRunner: 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
02-02 12:28:41.328 19653 19675 E TestRunner: 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
02-02 12:28:41.328 19653 19675 E TestRunner: 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
02-02 12:28:41.328 19653 19675 E TestRunner: 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
02-02 12:28:41.328 19653 19675 E TestRunner: 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
02-02 12:28:41.328 19653 19675 E TestRunner: 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
02-02 12:28:41.328 19653 19675 E TestRunner: 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
02-02 12:28:41.328 19653 19675 E TestRunner: 	at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:162)
02-02 12:28:41.328 19653 19675 E TestRunner: 	at org.junit.runners.Suite.runChild(Suite.java:128)
02-02 12:28:41.328 19653 19675 E TestRunner: 	at org.junit.runners.Suite.runChild(Suite.java:27)
02-02 12:28:41.328 19653 19675 E TestRunner: 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
02-02 12:28:41.328 19653 19675 E TestRunner: 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
02-02 12:28:41.328 19653 19675 E TestRunner: 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
02-02 12:28:41.328 19653 19675 E TestRunner: 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
02-02 12:28:41.328 19653 19675 E TestRunner: 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
02-02 12:28:41.328 19653 19675 E TestRunner: 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
02-02 12:28:41.328 19653 19675 E TestRunner: 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
02-02 12:28:41.328 19653 19675 E TestRunner: 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
02-02 12:28:41.328 19653 19675 E TestRunner: 	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
02-02 12:28:41.328 19653 19675 E TestRunner: 	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:444)
02-02 12:28:41.328 19653 19675 E TestRunner: 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2279)
02-02 12:28:41.328 19653 19675 E TestRunner: ----- end exception -----
02-02 12:28:41.330 19653 19675 I TestRunner: finished: addText(com.google.modernstorage.storage.SharedMediaStoreTest)

java.io.EOFException
at okio.RealBufferedSource.require(RealBufferedSource.kt:199)
at okio.RealBufferedSource.readByte(RealBufferedSource.kt:209)
at com.google.modernstorage.storage.SharedMediaStoreTest.addFile(SharedMediaStoreTest.kt:72)
at com.google.modernstorage.storage.SharedMediaStoreTest.addText(SharedMediaStoreTest.kt:109)
```

I though initially that Android platform was doing something weird with text files but replacing the line mentioned earlier by this one makes the test working successfully:
```kotlin
appContext.assets.open("sample.$extension").source().buffer().readAll(fileSystem.sink(path))
```

<img width="567" alt="image" src="https://user-images.githubusercontent.com/1113976/152146447-2a13be48-25e2-4d94-accb-252cb4e6eba7.png">

I didn't fully investigate where the issue may be, but is it related to the fact that text files might not be treated the same as binary files?

**Comment by JakeWharton** [comment]
You're missing a call to `close()` which will flush the buffer. When you invert the calls, you are not buffering the writes to the sink and `readAll` will exhaust the buffered source.

**Comment by yrezgui** [comment]
Thanks @JakeWharton, it solved the issue!
Regarding the reason why only my text file test was failing is the buffer segment size (`Segment.SIZE = 8192`), my text file was only 4 KB. The other files being bigger, the buffer was automatically flushed 😅

**Comment by JakeWharton** [comment]
Ah yeah. Complete segments are automatically propagated as you go, but you still need the flush (or close) for the last segment which is likely partially full. For example, if you had a file of 8193 bytes you would have seen a text file of 8192 bytes with a single byte left unwritten in the buffer.
