### ISSUE TITLE
Fatal Exception: java.lang.VerifyError  (Android 9)

### ISSUE THREAD

**Issue by GrowJayesh** [square/okio#1148]
Fatal Exception: java.lang.VerifyError: Verifier rejected class okio.Buffer: okio.BufferedSink okio.Buffer.write(byte[], int, int): [0xFFFFFFFF] bad register counts (ins=4 regs=0 (declaration of 'okio.Buffer' appears in base.apk!classes4.dex)
       at okhttp3.ResponseBody$Companion.create(ResponseBody.kt:248)
       at okhttp3.ResponseBody$Companion.create$default(ResponseBody.kt:247)
       at okhttp3.internal.Util.<clinit>(Util.kt:67)
       at okhttp3.internal.Util.immutableListOf()
       at okhttp3.OkHttpClient.<clinit>(OkHttpClient.kt:1073)
       at com.google.firebase.crashlytics.internal.network.HttpRequest.<clinit>(HttpRequest.java:43)
       at com.google.firebase.crashlytics.internal.network.HttpRequestFactory.buildHttpRequest(HttpRequestFactory.java:43)
       at com.google.firebase.crashlytics.internal.common.AbstractSpiCall.getHttpRequest(AbstractSpiCall.java:113)
       at com.google.firebase.crashlytics.internal.settings.network.DefaultSettingsSpiCall.invoke(DefaultSettingsSpiCall.java:80)
       at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:200)
       at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:193)
       at com.google.android.gms.tasks.zzo.run(com.google.android.gms:play-services-tasks@@17.2.1:1)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:60)
       at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:27)
       at java.lang.Thread.run(Thread.java:764)

**Comment by swankjesse** [comment]
Weird. Compiler bug?

**Comment by swankjesse** [comment]
No obvious action to take on this.
