### ISSUE TITLE
java.net.SocketException: Software caused connection abort

### ISSUE THREAD

**Issue by hamed-rv** [square/okio#1167]
I got this crash on Firebase with this log and details:

Device: Samsung, Galaxy Tab A7 Lite
Android 12 API 31
```
Fatal Exception: java.net.SocketException: Software caused connection abort
       at java.net.SocketInputStream.socketRead0(SocketInputStream.java)
       at java.net.SocketInputStream.socketRead(SocketInputStream.java:118)
       at java.net.SocketInputStream.read(SocketInputStream.java:173)
       at java.net.SocketInputStream.read(SocketInputStream.java:143)
       at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:945)
       at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:909)
       at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:824)
       at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:797)
       at okio.InputStreamSource.read(JvmOkio.kt:90)
       at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:129)
       at okio.RealBufferedSource.request(RealBufferedSource.kt:206)
       at okio.RealBufferedSource.require(RealBufferedSource.kt:199)
       at okhttp3.internal.http2.Http2Reader.nextFrame(Http2Reader.kt:89)
       at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:618)
       at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:609)
       at okhttp3.internal.concurrent.TaskQueue$execute$1.runOnce(TaskQueue.kt:98)
       at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:116)
       at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
       at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:65)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)
```

**Comment by YevhenHoltsev** [comment]
The same here.
A Crashlytics says it's a fresh issue (for my project the dependency was upgraded 2.8.0 -> 3.2.0.

**Comment by sokolarab** [comment]
@YevhenHoltsev 
which dependence you upgrade?

**Comment by YevhenHoltsev** [comment]
@sokolarab Hello, it was `com.squareup.okio:okio`.
I put it wrong in my comment, an update was from 2.2.2 to 3.2.0.

After reverting back to 2.2.2 things are back to normal.

**Comment by kbaljeet** [comment]
I'm having this same issue but I'm not using "com.squareup.okio:okio" dependency- instead my app have
"`com.squareup.okhttp3:okhttp:4.9.0`" 
and moshi _`com.squareup.moshi:moshi:1.12.0`_

**Comment by ashutoshkumardev** [comment]
I am also facing the same issue from last couple of weeks but not with com.squareup.okio:okio 
but instead using the below dependencies:-

    implementation('com.squareup.retrofit2:retrofit:2.9.0') {
        exclude module: 'okhttp'
    }
    implementation 'com.squareup.retrofit2:adapter-rxjava2:2.3.0'
    implementation 'com.squareup.okhttp3:okhttp:4.2.1'
    implementation 'com.squareup.okhttp3:logging-interceptor:4.2.1'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'

**Comment by bhumeshvr7github** [comment]
I am also facing this issue on **Redmi Y2** device

My gradle-
implementation 'com.squareup.retrofit2:retrofit:2.9.0'
implementation 'com.squareup.retrofit2:converter-gson:2.9.0'
implementation 'com.squareup.okhttp3:logging-interceptor:4.10.0'
implementation 'com.squareup.retrofit2:converter-scalars:2.7.2'

Fatal Exception: java.net.SocketException
**Software caused connection abort**
java.net.SocketInputStream.socketRead0 (SocketInputStream.java)

java.net.SocketInputStream.read (SocketInputStream.java:144)
okio.InputStreamSource.read (JvmOkio.kt:94)
okio.AsyncTimeout$source$1.read (AsyncTimeout.kt:125)
okio.RealBufferedSource.read (RealBufferedSource.kt:189)
okhttp3.internal.http1.Http1ExchangeCodec$AbstractSource.read (Http1ExchangeCodec.kt:331)
okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.read (Http1ExchangeCodec.kt:412)
okhttp3.internal.connection.Exchange$ResponseBodySource.read (Exchange.kt:276)
okio.RealBufferedSource.read (RealBufferedSource.kt:189)
okio.RealBufferedSource.exhausted (RealBufferedSource.kt:197)
okio.InflaterSource.refill (InflaterSource.kt:112)
okio.InflaterSource.readOrInflate (InflaterSource.kt:76)
okio.InflaterSource.read (InflaterSource.kt:49)
okio.GzipSource.read (GzipSource.kt:69)
okio.RealBufferedSource.read (RealBufferedSource.kt:189)
okio.ForwardingSource.read (ForwardingSource.kt:29)
retrofit2.OkHttpCall$ExceptionCatchingResponseBody$1.read (OkHttpCall.java:314)
okio.Buffer.writeAll (Buffer.kt:1290)
okio.RealBufferedSource.readString (RealBufferedSource.kt:95)
okhttp3.ResponseBody.string (ResponseBody.kt:187)
retrofit2.converter.scalars.ScalarResponseBodyConverters$StringResponseBodyConverter.convert (ScalarResponseBodyConverters.java:30)
retrofit2.converter.scalars.ScalarResponseBodyConverters$StringResponseBodyConverter.convert (ScalarResponseBodyConverters.java:26)
retrofit2.OkHttpCall.parseResponse (OkHttpCall.java:243)
retrofit2.OkHttpCall$1.onResponse (OkHttpCall.java:153)
okhttp3.internal.connection.RealCall$AsyncCall.run (RealCall.kt:519)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)

java.lang.Thread.run (Thread.java:764)

**Comment by Danny2790** [comment]
I am also facing the issues on Pixel 5 OS 13, Galaxy S20 5G OS 13.

Please help me if any solution on this.

Non-fatal Exception: java.net.SocketException: Software caused connection abort
       at java.net.SocketInputStream.socketRead0(SocketInputStream.java)
       at java.net.SocketInputStream.socketRead(SocketInputStream.java:118)
       at java.net.SocketInputStream.read(SocketInputStream.java:173)
       at java.net.SocketInputStream.read(SocketInputStream.java:143)
       at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:945)
       at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:909)
       at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:824)
       at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:797)
       at okio.InputStreamSource.read(JvmOkio.kt:94)
       at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:128)
       at okio.RealBufferedSource.request(RealBufferedSource.kt:206)
       at okio.RealBufferedSource.require(RealBufferedSource.kt)
       at okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.kt:381)
       at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.readChunkSize(Http1ExchangeCodec.kt:431)
       at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.read(Http1ExchangeCodec.kt:410)
       at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:281)
       at okio.RealBufferedSource.read(RealBufferedSource.kt:189)
       at okio.ForwardingSource.read(ForwardingSource.kt:27)
       at retrofit2.OkHttpCall$ExceptionCatchingResponseBody$1.read(OkHttpCall.java)
       at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.kt:158)
       at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:291)
       at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:355)
       at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:181)
       at java.io.InputStreamReader.read(InputStreamReader.java:180)
       at okhttp3.ResponseBody$BomAwareReader.read(ResponseBody.kt:211)
       at com.google.gson.stream.JsonReader.fillBuffer(JsonReader.java:1300)
       at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1338)
       at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:548)
       at com.google.gson.stream.JsonReader.peek(JsonReader.java:435)
       at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:41)
       at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27)
       at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:243)
       at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:153)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:520)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)

**Comment by AkshShah1** [comment]
I am also facing a similar issue in **Galaxy S22 Ultra, Android 13**
Please can anyone help me on this

`Fatal Exception: java.net.SocketException: Software caused connection abort
       at java.net.SocketInputStream.socketRead0(SocketInputStream.java)
       at java.net.SocketInputStream.socketRead(SocketInputStream.java:118)
       at java.net.SocketInputStream.read(SocketInputStream.java:173)
       at java.net.SocketInputStream.read(SocketInputStream.java:143)
       at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:983)
       at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:947)
       at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:862)
       at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:835)
       at okio.InputStreamSource.read(JvmOkio.kt:94)
       at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:125)
       at okio.RealBufferedSource.request(RealBufferedSource.kt:206)
       at okio.RealBufferedSource.require(RealBufferedSource.kt:199)
       at okhttp3.internal.http2.Http2Reader.nextFrame(Http2Reader.kt:89)
       at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:618)
       at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:609)
       at okhttp3.internal.concurrent.TaskQueue$execute$1.runOnce(TaskQueue.kt:98)
       at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:116)
       at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
       at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:65)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at java.lang.Thread.run(Thread.java:1012)`

**Comment by git-kishan** [comment]
> I am also facing the issues on **Pixel 5 OS 13**, **Galaxy S20 5G OS 13**.
> 
> Please help me if any solution on this.
> 
> Non-fatal Exception: java.net.SocketException: Software caused connection abort at java.net.SocketInputStream.socketRead0(SocketInputStream.java) at java.net.SocketInputStream.socketRead(SocketInputStream.java:118) at java.net.SocketInputStream.read(SocketInputStream.java:173) at java.net.SocketInputStream.read(SocketInputStream.java:143) at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:945) at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:909) at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:824) at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:797) at okio.InputStreamSource.read(JvmOkio.kt:94) at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:128) at okio.RealBufferedSource.request(RealBufferedSource.kt:206) at okio.RealBufferedSource.require(RealBufferedSource.kt) at okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.kt:381) at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.readChunkSize(Http1ExchangeCodec.kt:431) at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.read(Http1ExchangeCodec.kt:410) at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:281) at okio.RealBufferedSource.read(RealBufferedSource.kt:189) at okio.ForwardingSource.read(ForwardingSource.kt:27) at retrofit2.OkHttpCall$ExceptionCatchingResponseBody$1.read(OkHttpCall.java) at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.kt:158) at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:291) at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:355) at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:181) at java.io.InputStreamReader.read(InputStreamReader.java:180) at okhttp3.ResponseBody$BomAwareReader.read(ResponseBody.kt:211) at com.google.gson.stream.JsonReader.fillBuffer(JsonReader.java:1300) at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1338) at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:548) at com.google.gson.stream.JsonReader.peek(JsonReader.java:435) at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:41) at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27) at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:243) at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:153) at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:520) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) at java.lang.Thread.run(Thread.java:1012)

@AkshShah1  did you found the solution for this ? I am facing same issue in huge numbers

**Comment by swap9391** [comment]
> > I am also facing the issues on **Pixel 5 OS 13**, **Galaxy S20 5G OS 13**.
> > Please help me if any solution on this.
> > Non-fatal Exception: java.net.SocketException: Software caused connection abort at java.net.SocketInputStream.socketRead0(SocketInputStream.java) at java.net.SocketInputStream.socketRead(SocketInputStream.java:118) at java.net.SocketInputStream.read(SocketInputStream.java:173) at java.net.SocketInputStream.read(SocketInputStream.java:143) at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:945) at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:909) at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:824) at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:797) at okio.InputStreamSource.read(JvmOkio.kt:94) at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:128) at okio.RealBufferedSource.request(RealBufferedSource.kt:206) at okio.RealBufferedSource.require(RealBufferedSource.kt) at okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.kt:381) at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.readChunkSize(Http1ExchangeCodec.kt:431) at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.read(Http1ExchangeCodec.kt:410) at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:281) at okio.RealBufferedSource.read(RealBufferedSource.kt:189) at okio.ForwardingSource.read(ForwardingSource.kt:27) at retrofit2.OkHttpCall$ExceptionCatchingResponseBody$1.read(OkHttpCall.java) at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.kt:158) at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:291) at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:355) at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:181) at java.io.InputStreamReader.read(InputStreamReader.java:180) at okhttp3.ResponseBody$BomAwareReader.read(ResponseBody.kt:211) at com.google.gson.stream.JsonReader.fillBuffer(JsonReader.java:1300) at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1338) at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:548) at com.google.gson.stream.JsonReader.peek(JsonReader.java:435) at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:41) at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27) at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:243) at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:153) at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:520) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) at java.lang.Thread.run(Thread.java:1012)
> 
> [@AkshShah1](https://github.com/AkshShah1) did you found the solution for this ? I am facing same issue in huge numbers

I have faced same crash for **Vivo Y56 5G on Android 14** Any solution ?

Fatal Exception: java.net.SocketException: Software caused connection abort
       at java.net.SocketInputStream.socketRead0(SocketInputStream.java)
       at java.net.SocketInputStream.socketRead(SocketInputStream.java:118)
       at java.net.SocketInputStream.read(SocketInputStream.java:173)
       at java.net.SocketInputStream.read(SocketInputStream.java:143)
       at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:983)
       at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:947)
       at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:862)
       at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:835)
       at okio.InputStreamSource.read(JvmOkio.kt:94)
       at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:125)
       at okio.internal._RealBufferedSourceKt.commonRequest(_RealBufferedSource.kt:60)
       at okio.RealBufferedSource.request(RealBufferedSource.kt:68)
       at okio.internal._RealBufferedSourceKt.commonRequire(_RealBufferedSource.kt)
       at okio.RealBufferedSource.require(RealBufferedSource.kt)
       at okio.internal._RealBufferedSourceKt.commonReadHexadecimalUnsignedLong(_RealBufferedSource.kt:276)
       at okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.kt:115)
       at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.readChunkSize(Http1ExchangeCodec.kt:429)
       at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.read(Http1ExchangeCodec.kt:408)
       at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:276)
       at okio.internal._RealBufferedSourceKt.commonRead(_RealBufferedSource.kt:39)
       at okio.RealBufferedSource.read(RealBufferedSource.kt:65)
       at okio.ForwardingSource.read(ForwardingSource.kt:29)
       at retrofit2.OkHttpCall$ExceptionCatchingResponseBody$1.read(OkHttpCall.java:314)
       at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.kt:158)
       at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:291)
       at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:355)
       at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:181)
       at java.io.InputStreamReader.read(InputStreamReader.java:177)
       at okhttp3.ResponseBody$BomAwareReader.read(ResponseBody.kt:211)

**Comment by swap9391** [comment]
@hamed-rv @git-kishan @AkshShah1 


I have faced same crash for **Vivo Y56 5G on Android 14** Any solution ?

Fatal Exception: java.net.SocketException: Software caused connection abort
at java.net.SocketInputStream.socketRead0(SocketInputStream.java)
at java.net.SocketInputStream.socketRead(SocketInputStream.java:118)
at java.net.SocketInputStream.read(SocketInputStream.java:173)
at java.net.SocketInputStream.read(SocketInputStream.java:143)
at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:983)
at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:947)
at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:862)
at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:835)
at okio.InputStreamSource.read(JvmOkio.kt:94)
at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:125)
at okio.internal._RealBufferedSourceKt.commonRequest(_RealBufferedSource.kt:60)
at okio.RealBufferedSource.request(RealBufferedSource.kt:68)
at okio.internal._RealBufferedSourceKt.commonRequire(_RealBufferedSource.kt)
at okio.RealBufferedSource.require(RealBufferedSource.kt)
at okio.internal._RealBufferedSourceKt.commonReadHexadecimalUnsignedLong(_RealBufferedSource.kt:276)
at okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.kt:115)
at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.readChunkSize(Http1ExchangeCodec.kt:429)
at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.read(Http1ExchangeCodec.kt:408)
at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:276)
at okio.internal._RealBufferedSourceKt.commonRead(_RealBufferedSource.kt:39)
at okio.RealBufferedSource.read(RealBufferedSource.kt:65)
at okio.ForwardingSource.read(ForwardingSource.kt:29)
at retrofit2.OkHttpCall$ExceptionCatchingResponseBody$1.read(OkHttpCall.java:314)
at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.kt:158)
at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:291)
at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:355)
at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:181)
at java.io.InputStreamReader.read(InputStreamReader.java:177)
at okhttp3.ResponseBody$BomAwareReader.read(ResponseBody.kt:211)

**Comment by JakeWharton** [comment]
These exceptions are not caused by Okio, as evidenced by it not being at the tip of the stack trace. This means the remove server closed the connection while you were reading. It's a normal exception that you should handle, along work other general transport-related IOExceptions.

**Comment by Bruce-7-tech** [comment]
> These exceptions are not caused by Okio, as evidenced by it not being at the tip of the stack trace. This means the remove server closed the connection while you were reading. It's a normal exception that you should handle, along work other general transport-related IOExceptions.

Thank you for the explanation!

Could you kindly advise on the best practice for handling this type of exception?
Would it be reasonable to automatically attempt to reconnect the WebSocket, or is there a preferred strategy in such scenarios?

I really appreciate your help — thank you!

**Comment by JakeWharton** [comment]
Such a decision is entirely up to your application and the server you are talking to and its policy.

For a web socket, generally, performing automatic reconnection on transport errors is expected usually along with appropriate messaging to the user while this is happening. You also should have a back-off and permanently fail at _some_ point.

I'll also note that none of the stack traces in this issue have been web sockets but instead HTTP/2 frame reads or waiting on the next chunk of a chunked HTTP/1 body. We don't know what they were doing, so automatically retrying might not be appropriate.

**Comment by Bruce-7-tech** [comment]
> Such a decision is entirely up to your application and the server you are talking to and its policy.
> 
> For a web socket, generally, performing automatic reconnection on transport errors is expected usually along with appropriate messaging to the user while this is happening. You also should have a back-off and permanently fail at _some_ point.
> 
> I'll also note that none of the stack traces in this issue have been web sockets but instead HTTP/2 frame reads or waiting on the next chunk of a chunked HTTP/1 body. We don't know what they were doing, so automatically retrying might not be appropriate.

Thanks a lot for the detailed reply — that makes things much clearer!

I'm a big fan of your work, and it's really great to hear directly from you. I’ve learned a lot from your projects over the years, so I truly appreciate your help here. 🙏
