### ISSUE TITLE
Unclosed Sink causes a StrictMode violation

### ISSUE THREAD

**Issue by Egorand** [square/okio#1228]
Noticed this in Cash App which is using Okio 3.3.0 at this time, full stack trace below. The stack trace has code from Cash, Chucker, OkHttp and Okio, so the issue might not be in Okio.

I'm able to repro this on an API 29 emulator, but not on an API 31 emulator - could it be an emulator issue?

```
StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
	at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1877)
	at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:286)
	at java.io.FileOutputStream.finalize(FileOutputStream.java:486)
	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:289)
	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:276)
	at java.lang.Daemons$Daemon.run(Daemons.java:137)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.Throwable: Explicit termination method 'close' not called
	at dalvik.system.CloseGuard.open(CloseGuard.java:237)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:252)
	at okio.Okio__JvmOkioKt.sink(JvmOkio.kt:174)
	at okio.Okio.sink(Unknown Source:1)
	at okio.Okio__JvmOkioKt.sink$default(JvmOkio.kt:174)
	at okio.Okio.sink$default(Unknown Source:1)
	at okio.JvmSystemFileSystem.sink(JvmSystemFileSystem.kt:100)
	at okio.ForwardingFileSystem.sink(ForwardingFileSystem.kt:206)
	at okhttp3.internal.cache.DiskLruCache$fileSystem$1.sink(DiskLruCache.kt:109)
	at okio.FileSystem.sink(FileSystem.kt:75)
	at okhttp3.internal._UtilCommonKt.isCivilized(-UtilCommon.kt:305)
	at okhttp3.internal.cache.DiskLruCache.initialize(DiskLruCache.kt:241)
	at okhttp3.internal.cache.DiskLruCache.get(DiskLruCache.kt:438)
	at okhttp3.Cache.get$okhttp(Cache.kt:177)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:48)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:65)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at com.chuckerteam.chucker.api.ChuckerInterceptor.intercept(ChuckerInterceptor.kt:114)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:233)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at com.squareup.cash.integration.api.CashApiInterceptor.intercept(CashApiInterceptor.kt:145)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at com.squareup.cash.integration.api.CommonInterceptor.intercept(CommonInterceptor.kt:26)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at com.squareup.cash.api.GzipRequestBodyInterceptor.intercept(GzipRequestBodyInterceptor.kt:26)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at com.squareup.cash.api.TimeoutOverrideInterceptor.intercept(TimeoutOverrideInterceptor.kt:22)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:205)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:533)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919) 
```

**Comment by swankjesse** [comment]
Fixed in 3.3.0. Unfortunately all libraries that built on earlier Okio releases must upgrade for the fix because the bug is in an `inline` function.
