### ISSUE TITLE
Fatal Exception: java.net.SocketException: Software caused connection abort

### ISSUE THREAD

**Issue by AkshShah1** [square/okio#1255]
Firebase Crashlytic Reported

Version: Android 13
```
Fatal Exception: java.net.SocketException: Software caused connection abort
       at java.net.SocketInputStream.socketRead0(SocketInputStream.java)
       at java.net.SocketInputStream.socketRead(SocketInputStream.java:118)
       at java.net.SocketInputStream.read(SocketInputStream.java:173)
       at java.net.SocketInputStream.read(SocketInputStream.java:143)
       at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:945)
       at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:909)
       at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:824)
       at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:797)
       at okio.InputStreamSource.read(JvmOkio.kt:94)
       at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:125)
       at okio.RealBufferedSource.read(RealBufferedSource.kt:189)
       at okhttp3.internal.http2.Http2Stream$FramingSource.receive$okhttp(Http2Stream.kt:445)
       at okhttp3.internal.http2.Http2Stream.receiveData(Http2Stream.kt:276)
       at okhttp3.internal.http2.Http2Connection$ReaderRunnable.data(Http2Connection.kt:650)
       at okhttp3.internal.http2.Http2Reader.readData(Http2Reader.kt:180)
       at okhttp3.internal.http2.Http2Reader.nextFrame(Http2Reader.kt:119)
       at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:618)
       at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:609)
       at okhttp3.internal.concurrent.TaskQueue$execute$1.runOnce(TaskQueue.kt:98)
       at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:116)
       at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
       at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:65)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)
```

**Comment by swankjesse** [comment]
Unclear what action to take here.
