### ISSUE TITLE
IllegalStateException in Timeout.deadlineNanoTime

### ISSUE THREAD

**Issue by damianw** [square/okio#133]
I'm currently using okhttp to handle network requests, but occasionally it crashes with the following. I can't seem to find anyone else with this issue, nor can I reproduce it reliably. Is this a situation where I should be setting request timeouts explicitly within okhttp, or is this an actual issue with okio?

If this should be an okhttp issue, let me know and I can post it there instead.

```
java.lang.IllegalStateException: No deadline
        at okio.Timeout.deadlineNanoTime(Timeout.java:104)
        at okio.AsyncTimeout.scheduleTimeout(AsyncTimeout.java:88)
        at okio.AsyncTimeout.enter(AsyncTimeout.java:69)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:209)
        at okio.RealBufferedSource.exhausted(RealBufferedSource.java:60)
        at com.squareup.okhttp.internal.http.HttpConnection.isReadable(HttpConnection.java:152)
        at com.squareup.okhttp.Connection.isReadable(Connection.java:305)
        at com.squareup.okhttp.OkHttpClient$1.isReadable(OkHttpClient.java:87)
        at com.squareup.okhttp.internal.http.RouteSelector.nextUnconnected(RouteSelector.java:143)
        at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:130)
        at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:312)
        at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:235)
        at com.squareup.okhttp.Call.getResponse(Call.java:262)
        at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:219)
        at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:192)
        at com.squareup.okhttp.Call.access$100(Call.java:34)
        at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:156)
        at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
```

**Comment by swankjesse** [comment]
Very interesting. It's a bug in our code somewhere. Will fix.

**Comment by damianw** [comment]
Alright, thanks!

**Comment by Krenair** [comment]
This is probably the most frequent Wikipedia app crash at the moment.

**Comment by swankjesse** [comment]
@damianw @Krenair it's a concurrency bug, but I'm having some trouble reasoning about it.

**Comment by swankjesse** [comment]
Good news; I figured out the bug. Though I haven't fixed it yet.

OkHttp pools socket connections. A socket connection will be lent out to one call, used, and when its response is exhausted it is returned to the connection pool.

Although we steal away the socket when something is returned to the pool, we foolishly use the same instance of Timeout. And so the thread that was using the socket is still interacting with the timeout when some other thread takes it over.

The solution is to not share timeout instances. I'll prep the fix tomorrow!

**Comment by swankjesse** [comment]
This is a problem in OkHttp. Will be fixed by https://github.com/square/okhttp/issues/1654.
