### ISSUE TITLE
Is possible read nullable?

### ISSUE THREAD

**Issue by heiha100** [square/okio#1332]
I am trying read a file that contain json string, and decode json mabey fail, so I tried retrun null when decoded failed. But it rasied a NullPoninterException. Here is my code:
```kotlin
           fileSystem.list(path).mapNotNull {
                fileSystem.read<CachedResponseData?>(it) {
                    try {
                        Json.decodeFromString<PersistentResponseData>(readUtf8()).toCache()
                    } catch (tr: Throwable) {
                        logw(TAG, "load local chache failed", tr)
                        null
                    }
                }
            }.toSet()
```

log:
```
java.lang.NullPointerException
	at top.heiha.huntun.hmage.cache.PersistentCacheStorage.findAll(PersistentCacheStorage.kt:143)
	at io.ktor.client.plugins.cache.HttpCache.findResponse(HttpCache.kt:328)
	at io.ktor.client.plugins.cache.HttpCache.access$findResponse(HttpCache.kt:43)
	at io.ktor.client.plugins.cache.HttpCache$Companion$install$1.invokeSuspend(HttpCache.kt:149)
	at io.ktor.client.plugins.cache.HttpCache$Companion$install$1.invoke(Unknown Source:15)
	at io.ktor.client.plugins.cache.HttpCache$Companion$install$1.invoke(Unknown Source:4)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:98)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
	at io.ktor.client.plugins.HttpSend$DefaultSender.execute(HttpSend.kt:138)
	at io.ktor.client.plugins.HttpRedirect$Plugin$install$1.invokeSuspend(HttpRedirect.kt:64)
	at io.ktor.client.plugins.HttpRedirect$Plugin$install$1.invoke(Unknown Source:15)
	at io.ktor.client.plugins.HttpRedirect$Plugin$install$1.invoke(Unknown Source:6)
	at io.ktor.client.plugins.HttpSend$InterceptedSender.execute(HttpSend.kt:116)
	at io.ktor.client.plugins.HttpCallValidator$Companion$install$3.invokeSuspend(HttpCallValidator.kt:151)
	at io.ktor.client.plugins.HttpCallValidator$Companion$install$3.invoke(Unknown Source:13)
	at io.ktor.client.plugins.HttpCallValidator$Companion$install$3.invoke(Unknown Source:6)
	at io.ktor.client.plugins.HttpSend$InterceptedSender.execute(HttpSend.kt:116)
	at io.ktor.client.plugins.HttpSend$Plugin$install$1.invokeSuspend(HttpSend.kt:104)
	at io.ktor.client.plugins.HttpSend$Plugin$install$1.invoke(Unknown Source:15)
	at io.ktor.client.plugins.HttpSend$Plugin$install$1.invoke(Unknown Source:4)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceedWith(SuspendFunctionGun.kt:88)
	at io.ktor.client.plugins.HttpCallValidator$Companion$install$1.invokeSuspend(HttpCallValidator.kt:130)
	at io.ktor.client.plugins.HttpCallValidator$Companion$install$1.invoke(Unknown Source:13)
	at io.ktor.client.plugins.HttpCallValidator$Companion$install$1.invoke(Unknown Source:4)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
	at io.ktor.client.plugins.HttpRequestLifecycle$Plugin$install$1.invokeSuspend(HttpRequestLifecycle.kt:38)
	at io.ktor.client.plugins.HttpRequestLifecycle$Plugin$install$1.invoke(Unknown Source:11)
	at io.ktor.client.plugins.HttpRequestLifecycle$Plugin$install$1.invoke(Unknown Source:4)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:98)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
	at io.ktor.client.HttpClient.execute$ktor_client_core(HttpClient.kt:191)
	at io.ktor.client.statement.HttpStatement.executeUnsafe(HttpStatement.kt:108)
	at io.ktor.client.statement.HttpStatement.execute(HttpStatement.kt:47)
	at io.ktor.client.statement.HttpStatement.execute(HttpStatement.kt:62)
	at top.heiha.huntun.hmage.HmageKt$Hmage$2$1.invokeSuspend(Hmage.kt:139)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
```

**Comment by swankjesse** [comment]
Unclear what action to take here.
