### ISSUE TITLE
Pausing the server causes SocketTimeoutException

### ISSUE THREAD

**Issue by johnjohndoe** [square/okio#139]
I noticed I can crash an Android app using Okio when I **pause** the corresponding server interface for debugging purposes. This might be something you want to look into.

``` java
java.net.SocketTimeoutException
D      at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488)
D      at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
D      at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
D      at okio.Okio$2.read(Okio.java:137)
D      at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
D      at okio.RealBufferedSource.indexOf(RealBufferedSource.java:295)
D      at okio.RealBufferedSource.indexOf(RealBufferedSource.java:289)
D      at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
D      at com.squareup.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:190)
D      at com.squareup.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
D      at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:830)
D      at com.squareup.okhttp.internal.http.HttpEngine.access$200(HttpEngine.java:95)
D      at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:823)
D      at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:684)
D      at com.squareup.okhttp.Call.getResponse(Call.java:272)
D      at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
D      at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
D      at com.squareup.okhttp.Call.execute(Call.java:79)
D      at retrofit.client.OkClient.execute(OkClient.java:53)
D      at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
D      at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
D      at retrofit.RestAdapter$RestHandler$1.invoke(RestAdapter.java:265)
D      at retrofit.RxSupport$2.run(RxSupport.java:55)
D      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
D      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
D      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
D      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
D      at retrofit.Platform$Android$2$1.run(Platform.java:142)
D      at java.lang.Thread.run(Thread.java:818)
```

The Android app uses `com.squareup.okhttp:okhttp-urlconnection:2.3.0`.

**Comment by swankjesse** [comment]
This is working exactly as intended. The point of the timeout is to throw an exception when your server doesn't respond in a timely fashion.

**Comment by johnjohndoe** [comment]
Can you tell where I would try-catch for the `SocketTimeoutException` when I use [Retrofit](https://github.com/square/retrofit) with [OkHttp](https://github.com/square/okhttp)? Somewhere with the `RestAdapter`? I cannot see it from the stacktrace.
