### ISSUE TITLE
`AwaitSignalTest.signaled` is flaky

### ISSUE THREAD

**Issue by JakeWharton** [square/okio#1509]
```
okio.AwaitSignalTest[jvm] > signaled[BASE][jvm] FAILED
    java.lang.AssertionError: expected:<1000.0> but was:<1381.7652080000844>
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:555)
        at org.junit.Assert.assertEquals(Assert.java:685)
        at okio.AwaitSignalTest.assertElapsed(AwaitSignalTest.kt:208)
        at okio.AwaitSignalTest.signaled(AwaitSignalTest.kt:57)
```

**Comment by JakeWharton** [comment]
```
AwaitSignalTest_Async[jvm] > signaled[jvm] FAILED
    java.lang.AssertionError: expected:<1000.0> but was:<1716.0534999999218>
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:555)
        at org.junit.Assert.assertEquals(Assert.java:685)
        at okio.AwaitSignalTest.assertElapsed(AwaitSignalTest.kt:202)
        at okio.AwaitSignalTest.access$assertElapsed(AwaitSignalTest.kt:31)
        at okio.AwaitSignalTest$signaled$SignaledTestFunction.invoke(AwaitSignalTest.kt:51)
        at okio.AwaitSignalTest_Async$intercept$CallSuperTestFunction.invoke(AwaitSignalTest.kt:31)
        at okio.AwaitSignalTest$intercept$ExecutorServiceTestFunction.invoke(AwaitSignalTest.kt:31)
        at okio.TestExecutor.intercept(TestExecutor.kt:48)
        at okio.AwaitSignalTest.intercept(AwaitSignalTest.kt:31)
        at okio.AwaitSignalTest_Async.intercept(AwaitSignalTest.kt:31)
```
