### ISSUE TITLE
`SocketTimeoutTest.writeWithTimeout` is flaky

### ISSUE THREAD

**Issue by JakeWharton** [square/okio#1510]
```
okio.SocketTimeoutTest[jvm] > writeWithTimeout[jvm] FAILED
    java.lang.AssertionError: elapsed: 751618625
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at okio.SocketTimeoutTest.writeWithTimeout(SocketTimeoutTest.kt:81)
```

**Comment by JakeWharton** [comment]
https://github.com/square/okio/actions/runs/11182275912/job/31089954050
