### ISSUE TITLE
`PipeTest.sourceBlocksOnSlowWriter` is flaky

### ISSUE THREAD

**Issue by JakeWharton** [square/okio#1518]
```
 okio.PipeTest[jvm] > sourceBlocksOnSlowWriter[jvm] FAILED
    java.lang.AssertionError: expected:<4000.0> but was:<4265.846875000047>
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:555)
        at org.junit.Assert.assertEquals(Assert.java:685)
        at okio.PipeTest.assertElapsed(PipeTest.kt:356)
        at okio.PipeTest.sourceBlocksOnSlowWriter(PipeTest.kt:343)
```

**Comment by JakeWharton** [comment]
```
 okio.PipeTest[jvm] > sinkBlocksOnSlowReader[jvm] FAILED
    java.lang.AssertionError: expected:<3000.0> but was:<3484.8014589999802>
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:555)
        at org.junit.Assert.assertEquals(Assert.java:685)
        at okio.PipeTest.assertElapsed(PipeTest.kt:356)
        at okio.PipeTest.sinkBlocksOnSlowReader(PipeTest.kt:171)
```

**Comment by JakeWharton** [comment]
https://github.com/square/okio/actions/runs/11182275912/job/31088199790?pr=1529

**Comment by JakeWharton** [comment]
Again https://github.com/square/okio/actions/runs/11334093069/job/31519563616

**Comment by JakeWharton** [comment]
Again https://github.com/square/okio/actions/runs/11391218746/job/31694519307
