### ISSUE TITLE
`CipherSource` can't support RSA？

### ISSUE THREAD

**Issue by kagg886** [square/okio#1555]
exception is
```shell
Block cipher required Cipher.RSA/ECB/NoPadding, mode: encryption, algorithm from: SunJCE
java.lang.IllegalArgumentException: Block cipher required Cipher.RSA/ECB/NoPadding, mode: encryption, algorithm from: SunJCE
	at okio.CipherSource.<init>(CipherSource.kt:32)
	at okio.Okio__JvmOkioKt.cipherSource(JvmOkio.kt:205)
	at okio.Okio.cipherSource(Unknown Source)
```

my usage is this:

```kotlin
val rsaCipher = Cipher.getInstance("RSA/ECB/NoPadding").apply {
                            init(
                                Cipher.ENCRYPT_MODE,
                                KeyFactory.getInstance("RSA").generatePublic(
                                    RSAPublicKeySpec(
                                        BigInteger(
                                            "00e0b509f6259df8642dbc35662901477df22677ec152b5ff68ace615bb7b725152b3ab17a876aea8a5aa76d2e417629ec4ee341f56135fccf695280104e0312ecbda92557c93870114af6c9d05c4f7f0c3685b7a46bee255932575cce10b424d813cfe4875d3e82047b97ddef52741d546b8e289dc6935b3ece0462db0a22b8e7",
                                            16
                                        ),
                                        BigInteger(
                                            "010001",
                                            16
                                        )
                                    )
                                )
                            )
                        }

 randomString(16).byteInputStream().source()
                                            .cipherSource(rsaCipher).buffer()
                                            .readByteString().hex().take(256),
```

then run the code, error occured

**Comment by swankjesse** [comment]
You’ll need to find a hybrid encryption implementation to do asymmetric keys with a stream. Here’s a quick overview on doing it with Tink: https://www.baeldung.com/google-tink#hybrid
