### ISSUE TITLE
AssertionError from Buffer.readByteArray()

### ISSUE THREAD

**Issue by benjamin-bader** [square/okio#190]
Hi, I'm not sure how to reproduce this, but we just saw a crash from Okio:

```
Package: com.corp.app.dogfood
Version Code: 127
Version Name: 2.0.34
Android: 6.0.1
Manufacturer: LGE
Model: Nexus 5X
Date: Fri Feb 12 18:09:31 EST 2016

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:309)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.AssertionError: java.io.EOFException
	at okio.c.readByteArray(Buffer.java:709)
	at ...
	at android.os.AsyncTask$2.call(AsyncTask.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
Caused by: java.io.EOFException
	at okio.c.readFully(Buffer.java:732)
	at okio.c.readByteArray(Buffer.java:720)
	at okio.c.readByteArray(Buffer.java:707)
```

The offending code is pretty innocuous:

```java
Buffer buf = new Buffer();
BinaryProtocol proto = new BinaryProtocol(buf, buf);
adapter.write(proto, msg);
byte[] data = buf.readByteArray();  // the line that crashes
```

where `BinaryProtocol` is a Thrift serializer, operating in-memory and in a single thread.  From my reading of Buffer.java, the only way this happens is if `head` is null and `size` is nonzero, which shouldn't happen.  Maybe a threading issue with Segment, possibly similar to #134?

I know this isn't much to go on - if there's any more info you'd like, I'm glad to provide it.

**Comment by swankjesse** [comment]
One sad consequence of the way we do segment recycling is that if any part of your code is sharing a buffer between threads in an unsafe way, the crash could pop up somewhere unrelated. I think we should fix Okio to thread-confine segment pools.

**Comment by benjamin-bader** [comment]
Ah, I see - the recycling is global, so that an unsafe operation on a Buffer somewhere over there can impact an entirely separate Buffer that only lives on one Thread over here.

Thanks for that - I'll check our Buffer usage in the meantime.  Confining Segment pools sounds sane, even if it would increase memory usage a bit.

**Comment by swankjesse** [comment]
Thread confining the segment pools is the fix here.
