### ISSUE TITLE
EOFException in com.android.okhttp.okio.RealBufferedSource.require(RealBufferedSource.java:64)

### ISSUE THREAD

**Issue by pengood** [square/okio#223]
Hi, I use Volley to get Json string from http://www.weather.com.cn/data/sk/101010100.html, but  EOFException throwed, some logs like these:
```
`06-13 02:22:06.712 29554-29657/com.my.demo D/pzhao: in read java.io.EOFException
06-13 02:22:06.712 29554-29657/com.my.demo W/System.err: java.io.EOFException
06-13 02:22:06.712 29554-29657/com.my.demo W/System.err:     at com.android.okhttp.okio.RealBufferedSource.require(RealBufferedSource.java:64)
06-13 02:22:06.712 29554-29657/com.my.demo W/System.err:     at com.android.okhttp.okio.RealBufferedSource.readIntLe(RealBufferedSource.java:237)
06-13 02:22:06.712 29554-29657/com.my.demo W/System.err:     at com.android.okhttp.okio.GzipSource.consumeTrailer(GzipSource.java:173)
06-13 02:22:06.712 29554-29657/com.my.demo W/System.err:     at com.android.okhttp.okio.GzipSource.read(GzipSource.java:92)
06-13 02:22:06.712 29554-29657/com.my.demo W/System.err:     at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:349)
06-13 02:22:06.712 29554-29657/com.my.demo W/System.err:     at java.io.InputStream.read(InputStream.java:162)
06-13 02:22:06.712 29554-29657/com.my.demo W/System.err:     at com.android.volley.toolbox.BasicNetwork.entityToBytes(BasicNetwork.java:269)
06-13 02:22:06.712 29554-29657/com.my.demo W/System.err:     at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:127)
06-13 02:22:06.712 29554-29657/com.my.demo W/System.err:     at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:112)`
```

And i catch the http responce is fine

```
HTTP/1.1 200 OK
Date: Tue, 07 Jun 2016 06:04:30 GMT
Server: nginx
Content-Type: text/html
Transfer-Encoding: chunked
Content-Encoding: gzip
Age: 519458
X-Via: 1.1 zhwt194:1 (Cdn Cache Server V2.0)
Connection: keep-alive

{"weatherinfo":{"city":"北京","cityid":"101010100","temp":"18","WD":"东南风","WS":"1级","SD":"17%","WSE":"1","time":"17:05","isRadar":"1","Radar":"JC_RADAR_AZ9010_JB","njd":"暂无实况","qy":"1011","rain":"0"}}
```

Is it okio bug?

**Comment by swankjesse** [comment]
My guess is the last bytes of your response were truncated. I wasn’t able to reproduce this.
