### ISSUE TITLE
I have a problem with using wire inside okio lib on new Android L developer preview.

### ISSUE THREAD

**Issue by hao-tian** [square/okio#265]
I have a problem with using wire inside okio lib on new Android L developer preview. It's crashing with exception:
` Caused by: java.lang.IllegalAccessError: Illegal class access ('okio.Buffer' attempting to access 'okio.SegmentPool') in attempt to invoke static method okio.Segment okio.SegmentPool.take() (declaration of 'okio.Buffer' appears in /data/app/com.zhunxiner-1.apk)
                                                                   at okio.Buffer.writableSegment(Buffer.java:1151)
                                                                   at okio.Buffer.writeUtf8(Buffer.java:849)
                                                                   at okio.Buffer.writeUtf8(Buffer.java:830)
                                                                   at okhttp3.FormBody.writeOrCountBytes(FormBody.java:91)
                                                                   at okhttp3.FormBody.contentLength(FormBody.java:66)
                                                                   at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:58)
                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                   at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                   at com.zhunxiner.api.interceptor.TokenInterceptor.intercept(TokenInterceptor.java:23)
                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                   at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
                                                                   at okhttp3.RealCall.execute(RealCall.java:60)
                                                                   at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
                                                                   at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:171)
                                                                   at rx.Subscriber.setProducer(Subscriber.java:211)
                                                                   at rx.Subscriber.setProducer(Subscriber.java:205)
                                                                   at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
                                                                   at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
                                                                   at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
                                                                   at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                                   at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
                                                                   at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
                                                                   at rx.Observable.unsafeSubscribe(Observable.java:10151)
                                                                   at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
                                                                   at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:228)
                                                                   at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152) 
                                                                   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265) 
                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                   at java.lang.Thread.run(Thread.java:818) `

**Comment by swankjesse** [comment]
Fixed in AOSP.
https://github.com/square/okhttp/issues/967
