### ISSUE TITLE
System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference  W/System.err:     at okio.Buffer.writeUtf8(Unknown Source)

### ISSUE THREAD

**Issue by fanOfDemo** [square/okio#288]
02-17 15:52:16.953 4830-5179/? W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
02-17 15:52:16.953 4830-5179/? W/System.err:     at okio.Buffer.writeUtf8(Unknown Source)
02-17 15:52:16.953 4830-5179/? W/System.err:     at okio.RealBufferedSink.writeUtf8(Unknown Source)
02-17 15:52:16.953 4830-5179/? W/System.err:     at okhttp3.internal.connection.RealConnection.newCodec(RealConnection.java:390)
02-17 15:52:16.953 4830-5179/? W/System.err:     at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:102)
02-17 15:52:16.953 4830-5179/? W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
02-17 15:52:16.953 4830-5179/? W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
02-17 15:52:16.953 4830-5179/? W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
02-17 15:52:16.953 4830-5179/? W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
02-17 15:52:16.953 4830-5179/? W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
02-17 15:52:16.953 4830-5179/? W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
02-17 15:52:16.953 4830-5179/? W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
02-17 15:52:16.953 4830-5179/? W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
02-17 15:52:16.953 4830-5179/? W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
02-17 15:52:16.953 4830-5179/? W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
02-17 15:52:16.953 4830-5179/? W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
02-17 15:52:16.953 4830-5179/? W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
02-17 15:52:16.953 4830-5179/? W/System.err:     at okhttp3.RealCall.execute(RealCall.java:63)
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
02-17 15:52:16.953 4830-5179/? W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
02-17 15:52:16.953 4830-5179/? W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-17 15:52:16.953 4830-5179/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
02-17 15:52:16.953 4830-5179/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
02-17 15:52:16.953 4830-5179/? W/System.err:     at java.lang.Thread.run(Thread.java:818)

**Comment by swankjesse** [comment]
Which version of OkHttp? Doesn't look like this is possible with OkHttp 3.6.

**Comment by swankjesse** [comment]
No action to take here.

**Comment by fanOfDemo** [comment]
I've solved this problem， because of the dependency conflicts between the plugin and the host,Serialization of a class in okhttp or okio  is inconsistent between plugin and the host，and I'll try to find out which class is inconsistent。

**Comment by mouhcinecherqui** [comment]
2019-06-13 11:23:26.543 2382-2418/com.example.sdsi.test W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.io.BufferedReader.read()' on a null object reference
2019-06-13 11:23:26.562 2382-2418/com.example.sdsi.test W/System.err:     at com.example.sdsi.test.telnetsimple.readUntil(telnetsimple.java:77)
2019-06-13 11:23:26.563 2382-2418/com.example.sdsi.test W/System.err:     at com.example.sdsi.test.telnetsimple.log(telnetsimple.java:49)
2019-06-13 11:23:26.564 2382-2418/com.example.sdsi.test W/System.err:     at com.example.sdsi.test.page$1$1.run(page.java:45)
2019-06-13 11:23:26.565 2382-2418/com.example.sdsi.test W/System.err:     at java.lang.Thread.run(Thread.java:761)
2019-06-13 11:23:26.566 2382-2418/com.example.sdsi.test W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.io.BufferedReader.read()' on a null object reference
2019-06-13 11:23:26.567 2382-2418/com.example.sdsi.test W/System.err:     at com.example.sdsi.test.telnetsimple.readUntil(telnetsimple.java:77)
2019-06-13 11:23:26.567 2382-2418/com.example.sdsi.test W/System.err:     at com.example.sdsi.test.telnetsimple.log(telnetsimple.java:50)
2019-06-13 11:23:26.568 2382-2418/com.example.sdsi.test W/System.err:     at com.example.sdsi.test.page$1$1.run(page.java:45)
2019-06-13 11:23:26.568 2382-2418/com.example.sdsi.test W/System.err:     at java.lang.Thread.run(Thread.java:761)
2019-06-13 11:23:26.569 2382-2418/com.example.sdsi.test W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.PrintWriter.println(java.lang.String)' on a null object reference
2019-06-13 11:23:26.570 2382-2418/com.example.sdsi.test W/System.err:     at com.example.sdsi.test.telnetsimple.write(telnetsimple.java:98)
2019-06-13 11:23:26.571 2382-2418/com.example.sdsi.test W/System.err:     at com.example.sdsi.test.telnetsimple.log(telnetsimple.java:51)
2019-06-13 11:23:26.571 2382-2418/com.example.sdsi.test W/System.err:     at com.example.sdsi.test.page$1$1.run(page.java:45)
2019-06-13 11:23:26.571 2382-2418/com.example.sdsi.test W/System.err:     at java.lang.Thread.run(Thread.java:761)
2019-06-13 11:23:26.572 2382-2418/com.example.sdsi.test W/System.err: java.lang.NullPointerException
2019-06-13 11:23:26.573 2382-2418/com.example.sdsi.test W/System.err:  at java.io.Writer.<init>(Writer.java:88)
2019-06-13 11:23:26.607 2382-2418/com.example.sdsi.test W/System.err: at java.io.OutputStreamWriter.<init>(OutputStreamWriter.java:109)
2019-06-13 11:23:26.608 2382-2418/com.example.sdsi.test W/System.err: at com.example.sdsi.test.telnetsimple.aff(telnetsimple.java:122)
2019-06-13 11:23:26.608 2382-2418/com.example.sdsi.test W/System.err:  at com.example.sdsi.test.telnetsimple.log(telnetsimple.java:55)
2019-06-13 11:23:26.609 2382-2418/com.example.sdsi.test W/System.err:  at com.example.sdsi.test.page$1$1.run(page.java:45)
2019-06-13 11:23:26.609 2382-2418/com.example.sdsi.test W/System.err:  at java.lang.Thread.run(Thread.java:761)

**Comment by mouhcinecherqui** [comment]
a solution
