### ISSUE TITLE
java.lang.StackOverflowError okio.Okio$2.read (Okio.java:138) in Android 4 ONLY

### ISSUE THREAD

**Issue by gorshkovwork** [square/okio#290]
`Fatal Exception: java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
Caused by java.lang.StackOverflowError
       at java.net.Socket.checkOpenAndCreate(Socket.java:641)
       at java.net.Socket.getSoTimeout(Socket.java:435)
       at com.android.org.conscrypt.OpenSSLSocketImplWrapper.getSoTimeout(OpenSSLSocketImplWrapper.java:151)
       at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:689)
       at okio.Okio$2.read(Okio.java:138)
       at okio.AsyncTimeout$2.read(AsyncTimeout.java:236)
       at okio.RealBufferedSource.indexOf(RealBufferedSource.java:325)
       at okio.RealBufferedSource.indexOf(RealBufferedSource.java:314)
       at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210)
       at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
       at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:67)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:212)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at org.xbet.client1.di.module.ClientModule.lambda$getHttpClient$0(ClientModule.java:105)
       at org.xbet.client1.di.module.ClientModule.access$lambda$0(ClientModule.java)
       at org.xbet.client1.di.module.ClientModule$$Lambda$1.intercept(Unknown Source)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
       at okhttp3.RealCall.execute(RealCall.java:63)
       at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
       at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:40)
       at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24)
       at retrofit2.adapter.rxjava.BodyOnSubscribe.call(BodyOnSubscribe.java:33)
       at retrofit2.adapter.rxjava.BodyOnSubscribe.call(BodyOnSubscribe.java:25)
       at rx.Observable.unsafeSubscribe(Observable.java:10151)
       at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
       at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
       at rx.Observable.unsafeSubscribe(Observable.java:10151)
       at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
       at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
       at rx.Observable.unsafeSubscribe(Observable.java:10151)
       at rx.internal.operators.OnSubscribeRedo$2.call(OnSubscribeRedo.java:273)
       at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.enqueue(TrampolineScheduler.java:73)
       at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.schedule(TrampolineScheduler.java:52)
       at rx.internal.operators.OnSubscribeRedo$5.request(OnSubscribeRedo.java:361)
       at rx.Subscriber.setProducer(Subscriber.java:211)
       at rx.internal.operators.OnSubscribeRedo.call(OnSubscribeRedo.java:353)
       at rx.internal.operators.OnSubscribeRedo.call(OnSubscribeRedo.java:47)
       at rx.Observable.unsafeSubscribe(Observable.java:10151)
       at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:251)
       at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:148)
       at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
       at rx.internal.operators.OnSubscribeTimerPeriodically$1.call(OnSubscribeTimerPeriodically.java:52)
       at rx.Scheduler$Worker$1.call(Scheduler.java:137)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker$1.call(Scheduler.java:159)
       at rx.internal.schedulers.SleepingAction.call(SleepingAction.java:53)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:58)
       at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:53)
       at rx.Scheduler$Worker.schedulePeriodically(Scheduler.java:163)
       at rx.internal.operators.OnSubscribeTimerPeriodically.call(OnSubscribeTimerPeriodically.java:47)
       at rx.internal.operators.OnSubscribeTimerPeriodically.call(OnSubscribeTimerPeriodically.java:30)
       at rx.Observable.unsafeSubscribe(Observable.java:10151)
       at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
       at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
       at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
       at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
       at rx.Observable.unsafeSubscribe(Observable.java:10151)
       at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
       at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:228)
       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)`

**Comment by swankjesse** [comment]
I don't believe there's anything Okio can do here. Most of your stack frames are in Rx’s ImmediateScheduler. Perhaps you have a recursion problem there?
