### ISSUE TITLE
ArrayIndexOutOfBoundsException ==> regionLength=-1

### ISSUE THREAD

**Issue by razmaimon** [square/okio#292]
i get this error on a specific device: "TrendMicro - GI-I9500_TMMARS" on Android 5.1
web search suggests this is a bot and not a real device. 
crash log attached
[crash.txt](https://github.com/square/okio/files/823655/crash.txt)

Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=2048; regionStart=0; regionLength=-1
       at java.util.Arrays.checkOffsetAndCount(Arrays.java:1719)
       at libcore.io.IoBridge.write(IoBridge.java:491)
       at java.io.FileOutputStream.write(FileOutputStream.java:186)
       at java.util.MarsUtils.write(MarsUtils.java:33)
       at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:704)
       at okio.Okio$2.read(Okio.java:139)
       at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
       at okio.RealBufferedSource.request(RealBufferedSource.java:71)
       at okio.RealBufferedSource.require(RealBufferedSource.java:64)
       at okhttp3.internal.framed.Http2$Reader.nextFrame(Http2.java:111)
       at okhttp3.internal.framed.FramedConnection$Reader.execute(FramedConnection.java:600)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.lang.Thread.run(Thread.java:818)

**Comment by JakeWharton** [comment]
See https://github.com/square/okio/issues/221#issuecomment-274841608
