### ISSUE TITLE
java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)

### ISSUE THREAD

**Issue by AdrianAndroid** [square/okio#293]
java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)
 	 at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:545)
   	 at libcore.io.IoBridge.recvfrom(IoBridge.java:509)
 	 at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488)
 	 at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
 	 at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:240)
 	 at okio.Okio$2.read(Okio.java:154)
 	 at okio.AsyncTimeout$2.read(AsyncTimeout.java:259)
 	 at okio.RealBufferedSource.read(RealBufferedSource.java:51)
 	 at okio.RealBufferedSource.read(RealBufferedSource.java:51)
 	 at okio.RealBufferedSink.write(RealBufferedSink.java:106)
 	 at com.sainthigh.http.SaintOrderActivity$4.onResponse(SaintOrderActivity.java:234)
 	 at com.sainthigh.sainthttp.RealCall$AsyncCall.execute(RealCall.java:142)
 	 at com.sainthigh.sainthttp.internal.NamedRunnable.run(NamedRunnable.java:19)
 	 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
 	 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
 	 at java.lang.Thread.run(Thread.java:841)
 Caused by: libcore.io.ErrnoException: recvfrom failed: ECONNRESET (Connection reset by peer)
 	 at libcore.io.Posix.recvfromBytes(Native Method)
 	 at libcore.io.Posix.recvfrom(Posix.java:141)
 	 at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:164)
 	 at libcore.io.IoBridge.recvfrom(IoBridge.java:506)
 	 ... 14 more

**Comment by swankjesse** [comment]
Nothing actionable here. If you believe there's something OkHttp should do differently, please provide an executable test case.

**Comment by evoxmusic** [comment]
I got the same error..
