### ISSUE TITLE
SocketTimeoutException Okio when listening to endless stream

### ISSUE THREAD

**Issue by CharlottaSpik** [square/okio#301]
I am trying to listen to a streaming API, but because this API is a bit slow with emitting items I get a TimeoutException when an item hasn't been emitted for a while. I am using rxJava and Okio. I have set the timeout for both these libraries but still get an exception. The problem seems to be Okio if you look at the stack trace. I have used Okio BufferedSource.

Stack trace:

java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
	at okio.RealBufferedSource.request(RealBufferedSource.java:71)
	at okio.RealBufferedSource.require(RealBufferedSource.java:64)
	at okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:270)
	at okhttp3.internal.http1.Http1Codec$ChunkedSource.readChunkSize(Http1Codec.java:444)
	at okhttp3.internal.http1.Http1Codec$ChunkedSource.read(Http1Codec.java:425)
	at okio.RealBufferedSource.read(RealBufferedSource.java:50)
	at okio.ForwardingSource.read(ForwardingSource.java:35)
	at retrofit2.OkHttpCall$ExceptionCatchingRequestBody$1.read(OkHttpCall.java:285)
	at okio.RealBufferedSource.exhausted(RealBufferedSource.java:60)
	at com.example.meetup.MeetupListener$1.call(MeetupListener.java:142)
	at com.example.meetup.MeetupListener$1.call(MeetupListener.java:136)
	at rx.Observable.unsafeSubscribe(Observable.java:8666)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:250)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:147)
	at rx.internal.operators.OperatorMap$MapSubscriber.onNext(OperatorMap.java:74)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:505)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:463)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:246)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:147)
	at rx.internal.operators.OperatorMap$MapSubscriber.onNext(OperatorMap.java:74)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:146)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:125)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:8759)
	at rx.Observable.subscribe(Observable.java:8726)
	at rx.Observable.subscribe(Observable.java:8549)
	at com.example.meetup.MeetupListener.<init>(MeetupListener.java:127)
	at com.example.meetup.MeetupApplication.main(MeetupApplication.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Exception in thread "main" rx.exceptions.OnErrorNotImplementedException: Read timed out
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
	at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:157)
	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
	at rx.observers.SerializedObserver.onError(SerializedObserver.java:158)
	at rx.observers.SerializedSubscriber.onError(SerializedSubscriber.java:79)
	at rx.internal.operators.OperatorTimeoutBase$TimeoutSubscriber.onError(OperatorTimeoutBase.java:148)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.reportError(OperatorMerge.java:268)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.checkTerminate(OperatorMerge.java:812)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:573)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:562)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onError(OperatorMerge.java:846)
	at com.example.meetup.MeetupListener$1.call(MeetupListener.java:153)
	at com.example.meetup.MeetupListener$1.call(MeetupListener.java:136)
	at rx.Observable.unsafeSubscribe(Observable.java:8666)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:250)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:147)
	at rx.internal.operators.OperatorMap$MapSubscriber.onNext(OperatorMap.java:74)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:505)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:463)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:246)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:147)
	at rx.internal.operators.OperatorMap$MapSubscriber.onNext(OperatorMap.java:74)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:146)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:125)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:8759)
	at rx.Observable.subscribe(Observable.java:8726)
	at rx.Observable.subscribe(Observable.java:8549)
	at com.example.meetup.MeetupListener.<init>(MeetupListener.java:127)
	at com.example.meetup.MeetupApplication.main(MeetupApplication.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
	at okio.RealBufferedSource.request(RealBufferedSource.java:71)
	at okio.RealBufferedSource.require(RealBufferedSource.java:64)
	at okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:270)
	at okhttp3.internal.http1.Http1Codec$ChunkedSource.readChunkSize(Http1Codec.java:444)
	at okhttp3.internal.http1.Http1Codec$ChunkedSource.read(Http1Codec.java:425)
	at okio.RealBufferedSource.read(RealBufferedSource.java:50)
	at okio.ForwardingSource.read(ForwardingSource.java:35)
	at retrofit2.OkHttpCall$ExceptionCatchingRequestBody$1.read(OkHttpCall.java:285)
	at okio.RealBufferedSource.exhausted(RealBufferedSource.java:60)
	at com.example.meetup.MeetupListener$1.call(MeetupListener.java:142)
	... 32 more

**Comment by swankjesse** [comment]
What read timeout have you configured?

**Comment by CharlottaSpik** [comment]
I have configured timeout for rxJava and Okio using timeout(100, TimeUnit.SECONDS). I don't know what you mean with specifically read timeout. 

Thank you for replying!

**Comment by swankjesse** [comment]
Do you get this exception after 100 seconds? Does the problem go away if you disable the timeout/

**Comment by CharlottaSpik** [comment]
No to both questions. The timeout seems to appear when an item hasn't been emitted in a couple of seconds, usually around 10. I had the exception even before I added the timeouts. Adding the timeout for Okio did change the exception to the one I posted earlier. The full stack trace from the earlier exception before I added the Okio timeout is below.

java.net.SocketTimeoutException: timeout
	at okio.Okio$3.newTimeoutException(Okio.java:207)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:261)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
	at okio.RealBufferedSource.request(RealBufferedSource.java:71)
	at okio.RealBufferedSource.require(RealBufferedSource.java:64)
	at okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:270)
	at okhttp3.internal.http1.Http1Codec$ChunkedSource.readChunkSize(Http1Codec.java:444)
	at okhttp3.internal.http1.Http1Codec$ChunkedSource.read(Http1Codec.java:425)
	at okio.RealBufferedSource.read(RealBufferedSource.java:50)
	at okio.ForwardingSource.read(ForwardingSource.java:35)
	at retrofit2.OkHttpCall$ExceptionCatchingRequestBody$1.read(OkHttpCall.java:285)
	at okio.RealBufferedSource.exhausted(RealBufferedSource.java:60)
	at com.example.meetup.MeetupListener$1.call(MeetupListener.java:141)
	at com.example.meetup.MeetupListener$1.call(MeetupListener.java:135)
	at rx.Observable.unsafeSubscribe(Observable.java:8666)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:250)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:147)
	at rx.internal.operators.OperatorMap$MapSubscriber.onNext(OperatorMap.java:74)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:505)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:463)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:246)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:147)
	at rx.internal.operators.OperatorMap$MapSubscriber.onNext(OperatorMap.java:74)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:146)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:125)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:8759)
	at rx.Observable.subscribe(Observable.java:8726)
	at rx.Observable.subscribe(Observable.java:8549)
	at com.example.meetup.MeetupListener.<init>(MeetupListener.java:127)
	at com.example.meetup.MeetupApplication.main(MeetupApplication.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
	... 44 more
Exception in thread "RxComputationScheduler-2" java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: rx.exceptions.OnErrorNotImplementedException
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
	at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:157)
	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
	at rx.observers.SerializedObserver.onError(SerializedObserver.java:158)
	at rx.observers.SerializedSubscriber.onError(SerializedSubscriber.java:79)
	at rx.internal.operators.OperatorBufferWithTime$ExactSubscriber.onError(OperatorBufferWithTime.java:258)
	at rx.observers.SerializedObserver.onError(SerializedObserver.java:158)
	at rx.observers.SerializedSubscriber.onError(SerializedSubscriber.java:79)
	at rx.internal.operators.OperatorTimeoutBase$TimeoutSubscriber.onTimeout(OperatorTimeoutBase.java:178)
	at rx.internal.operators.OperatorTimeout$2$1.call(OperatorTimeout.java:54)
	at rx.internal.schedulers.EventLoopsScheduler$EventLoopWorker$2.call(EventLoopsScheduler.java:187)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	... 7 more
Caused by: java.util.concurrent.TimeoutException
	... 11 more

**Comment by swankjesse** [comment]
Did you try calling this API?
https://square.github.io/okhttp/3.x/okhttp/okhttp3/OkHttpClient.Builder.html#readTimeout-long-java.util.concurrent.TimeUnit-

**Comment by CharlottaSpik** [comment]
I have used retrofit builder and not okHttp builder so I am not sure how that would work. I have only used responeBody from okHttp3 and BufferedSource.

**Comment by JakeWharton** [comment]
You can pass a custom OkHttpClient to Retrofit's Builder with custom
timeouts set.

**Comment by CharlottaSpik** [comment]
How would I do that? This is the code for my builder:

        Service = new Retrofit.Builder()
                .baseUrl(baseURL)
                .addCallAdapterFactory(RxJavaCallAdapterFactory.create())
                .build()
                .create(Service.class);

**Comment by JakeWharton** [comment]
http://square.github.io/retrofit/2.x/retrofit/retrofit2/Retrofit.Builder.html#client-okhttp3.OkHttpClient-

**Comment by CharlottaSpik** [comment]
Thank you both for your help! This solved the sockettimeoutexception but I now got the EOFexception below instead after several hours of streaming. I know the stream didn't end as it is an endless stream and it isn't an internet connection issue as I tried disconnecting and it led to a java.net.SocketException: Software caused connection abort: recv failed.

Stacktrace: 

java.io.EOFException
	at okio.RealBufferedSource.require(RealBufferedSource.java:64)
	at okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:270)
	at okhttp3.internal.http1.Http1Codec$ChunkedSource.readChunkSize(Http1Codec.java:444)
	at okhttp3.internal.http1.Http1Codec$ChunkedSource.read(Http1Codec.java:425)
	at okio.RealBufferedSource.read(RealBufferedSource.java:50)
	at okio.ForwardingSource.read(ForwardingSource.java:35)
	at retrofit2.OkHttpCall$ExceptionCatchingRequestBody$1.read(OkHttpCall.java:285)
	at okio.RealBufferedSource.exhausted(RealBufferedSource.java:60)
	at com.example.meetup.MeetupListener$1.call(MeetupListener.java:159)
	at com.example.meetup.MeetupListener$1.call(MeetupListener.java:153)
	at rx.Observable.unsafeSubscribe(Observable.java:8666)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:250)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:147)
	at rx.internal.operators.OperatorMap$MapSubscriber.onNext(OperatorMap.java:74)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:505)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:463)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:246)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:147)
	at rx.internal.operators.OperatorMap$MapSubscriber.onNext(OperatorMap.java:74)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:146)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:125)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:8759)
	at rx.Observable.subscribe(Observable.java:8726)
	at rx.Observable.subscribe(Observable.java:8549)
	at com.example.meetup.MeetupListener.<init>(MeetupListener.java:144)
	at com.example.meetup.MeetupApplication.main(MeetupApplication.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Exception in thread "main" rx.exceptions.OnErrorNotImplementedException
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
	at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:157)
	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.reportError(OperatorMerge.java:268)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.checkTerminate(OperatorMerge.java:812)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:573)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:562)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onError(OperatorMerge.java:846)
	at com.example.meetup.MeetupListener$1.call(MeetupListener.java:170)
	at com.example.meetup.MeetupListener$1.call(MeetupListener.java:153)
	at rx.Observable.unsafeSubscribe(Observable.java:8666)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:250)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:147)
	at rx.internal.operators.OperatorMap$MapSubscriber.onNext(OperatorMap.java:74)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:505)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:463)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:246)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:147)
	at rx.internal.operators.OperatorMap$MapSubscriber.onNext(OperatorMap.java:74)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:146)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:125)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:8759)
	at rx.Observable.subscribe(Observable.java:8726)
	at rx.Observable.subscribe(Observable.java:8549)
	at com.example.meetup.MeetupListener.<init>(MeetupListener.java:144)
	at com.example.meetup.MeetupApplication.main(MeetupApplication.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.io.EOFException
	at okio.RealBufferedSource.require(RealBufferedSource.java:64)
	at okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:270)
	at okhttp3.internal.http1.Http1Codec$ChunkedSource.readChunkSize(Http1Codec.java:444)
	at okhttp3.internal.http1.Http1Codec$ChunkedSource.read(Http1Codec.java:425)
	at okio.RealBufferedSource.read(RealBufferedSource.java:50)
	at okio.ForwardingSource.read(ForwardingSource.java:35)
	at retrofit2.OkHttpCall$ExceptionCatchingRequestBody$1.read(OkHttpCall.java:285)
	at okio.RealBufferedSource.exhausted(RealBufferedSource.java:60)
	at com.example.meetup.MeetupListener$1.call(MeetupListener.java:159)
	... 30 more

**Comment by swankjesse** [comment]
Unclear what action to take here. If there’s something we should do, please provide a failing test case!

**Comment by louiewh** [comment]
okhttp-3.8.0, two-way ssl post large file to service 
if large file > 200M, happen this, small file no this problem:

                                                                          at okio.Okio$3.newTimeoutException(Okio.java:210)
                                                                          at okio.AsyncTimeout.exit(AsyncTimeout.java:277)
                                                                          at okio.AsyncTimeout$2.read(AsyncTimeout.java:244)
                                                                          at okio.RealBufferedSource.indexOf(RealBufferedSource.java:325)
                                                                          at okio.RealBufferedSource.indexOf(RealBufferedSource.java:314)
                                                                          at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210)
                                                                          at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
                                                                          at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:75)
                                                                          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.tools.profiler.support.network.okhttp.reflection.okhttp3.Interceptor$$Chain$.proceed(Interceptor$.java:52)
                                                                          at com.android.tools.profiler.support.network.okhttp.OkHttp3Interceptor.invoke(OkHttp3Interceptor.java:53)
                                                                          at java.lang.reflect.Proxy.invoke(Proxy.java:393)
                                                                          at $Proxy1.intercept(Unknown Source)
                                                                          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                          at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
                                                                          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                          at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
                                                                          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                          at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                                                          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                          at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
                                                                          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                          at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                          at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
                                                                          at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
                                                                          at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                          at java.lang.Thread.run(Thread.java:818)
