### ISSUE TITLE
App crash when using Facebook SDK

### ISSUE THREAD

**Issue by raunakyadav** [square/okio#302]
Hi , 
We are seeing the following exception quite frequently reported by our users. Please help if a fix is known for this.

Fatal Exception: java.lang.ArrayIndexOutOfBoundsException
       at com.android.okio.Util.checkOffsetAndCount(Util.java:29)
       at com.android.okio.Okio.copy(Okio.java:39)
       at com.android.okhttp.internal.http.HttpConnection$AbstractSource.cacheWrite(HttpConnection.java:378)
       at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:449)
       at com.android.okhttp.internal.Util.skipAll(Util.java:227)
       at com.android.okhttp.internal.http.HttpConnection.discard(HttpConnection.java:212)
       at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.close(HttpConnection.java:464)
       at com.android.okhttp.internal.Util.closeQuietly(Util.java:97)
       at com.android.okhttp.internal.http.HttpEngine.close(HttpEngine.java:439)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.disconnect(HttpURLConnectionImpl.java:113)
       at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.disconnect(DelegatingHttpsURLConnection.java:93)
       at com.android.okhttp.internal.http.HttpsURLConnectionImpl.disconnect(HttpsURLConnectionImpl.java:25)
       at com.facebook.ads.internal.h.b.h.b(Unknown Source)
       at com.facebook.ads.internal.h.b.k.h(Unknown Source)
       at com.facebook.ads.internal.h.b.k.e(Unknown Source)
       at com.facebook.ads.internal.h.b.k.a(Unknown Source)
       at com.facebook.ads.internal.h.b.k$a.run(Unknown Source)
       at java.lang.Thread.run(Thread.java:818)

**Comment by FabianTerhorst** [comment]
The crash seems pretty self explanatory. It also happened in your code and is not related to this library.

**Comment by JakeWharton** [comment]
Both of those statements are incorrect. The crash message is self-explanatory but the underlying cause is not. Also the trace pretty clearly indicates that this crash happened inside the version of Okio bundled into Android and that it's caused by the version of OkHttp bundled inside Android–neither being his code.

**Comment by swankjesse** [comment]
No action for us to take on this.
