### ISSUE TITLE
OutOfMemoryError: Could not allocate JNI Env. when create AsyncTimeout Watchdog Thread

### ISSUE THREAD

**Issue by sergio11** [square/okio#303]
Hi,

Unexpectedly my application crashes due to this error:

```
Caused by: java.lang.OutOfMemoryError: Could not allocate JNI Env
at java.lang.Thread.nativeCreate(Native Method)
at java.lang.Thread.start(Thread.java:1063)
at **okio.AsyncTimeout.scheduleTimeout(AsyncTimeout.java:87)**
at okio.AsyncTimeout.enter(AsyncTimeout.java:79)
at okio.AsyncTimeout$1.write(AsyncTimeout.java:177)
at okio.RealBufferedSink.flush(RealBufferedSink.java:216)
at okhttp3.internal.http1.Http1Codec.finishRequest(Http1Codec.java:166)
at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:64)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
at com.facebook.stetho.okhttp3.StethoInterceptor.intercept(StethoInterceptor.java:59)
```

Occurs when starting the WatchDog in the AsyncTimeout.
Can you tell me why the error occurs? 

Thanks in advance.

**Comment by swankjesse** [comment]
Looks like your program doesn't fit in memory. Either you're loading something into memory that you should be streaming, or you have a memory leak.

For more support please ask on StackOverflow.
