### ISSUE TITLE
GZip crash (found in Crashlytics)

### ISSUE THREAD

**Issue by KennyGoers** [square/okio#323]
I'm starting to see more instances of the following crash:

Caused by java.lang.NullPointerException
       at okio.GzipSource.updateCrc(GzipSource.java:189)
       at okio.GzipSource.read(GzipSource.java:82)
       at okio.RealBufferedSource$1.read(RealBufferedSource.java:430)
       at java.io.InputStreamReader.read(InputStreamReader.java:231)
       at java.io.BufferedReader.fillBuf(BufferedReader.java:145)
       at java.io.BufferedReader.readLine(BufferedReader.java:397)

Seeking pointers as to why this might be happening to start with. 

Seeing only in Android 4.4.2

Thanks,

**Comment by swankjesse** [comment]
All device manufacturers?

**Comment by KennyGoers** [comment]
Not all I think, but list includes Quanta, Acer,  ZTE, alps and PCD and still only 4.4.2

**Comment by donatienthorez** [comment]
I also encounter the same bug on Android 4.4.2 (96%) and also 4.4.1 (4%).

Here are the list of devices manufacturers I get : 
Acer,QMobile, InFocus, Panasonic,HTC, iBallMobile, TECNO, Micromax, Vodafone, bq, Gigabyte, Sony

**Comment by visiolink-android-dev** [comment]
Also seeing the same on Android 4.4 using okhttp 3.9.0 with stacktrace:

Caused by: java.lang.NullPointerException: 
  at okio.GzipSource.updateCrc (GzipSource.java:189)
  at okio.GzipSource.read (GzipSource.java:82)
  at okio.RealBufferedSource.request (RealBufferedSource.java:67)
  at okio.RealBufferedSource.rangeEquals (RealBufferedSource.java:408)
  at okio.RealBufferedSource.rangeEquals (RealBufferedSource.java:392)
  at okhttp3.internal.Util.bomAwareCharset (Util.java:449)

**Comment by swankjesse** [comment]
I wonder if it's caused by running out of memory in native code.

**Comment by visiolink-android-dev** [comment]
I guess the root cause of this is the same as https://github.com/square/okhttp/issues/3641

So probably this can also be worked around with:
`android.enableD8=false`

**Comment by JakeWharton** [comment]
s/worked around/temporarily avoided/

**Comment by visiolink-android-dev** [comment]
Confirmed to be temporarily avoided by disabling D8.

**Comment by swankjesse** [comment]
If anyone has a fix that prevents the problem, I’m receptive. Otherwise I think this is a problem in the platform.

**Comment by madsager** [comment]
Update from the D8 side on this one. Turns out the VM on these devices had yet another bug. We have landed a workaround for the VM bug in D8 which will be part of Android Studio 3.1 stable (and will make its way into android studio 3.2 over the next couple of weeks as well).

D8-side bug: https://issuetracker.google.com/75408029
