### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: src.length=8192 srcPos=87 dst.length=9 dstPos=0 length=-78

### ISSUE THREAD

**Issue by 317394245** [square/okio#329]
@Okio-1.13.0
java.lang.ArrayIndexOutOfBoundsException: src.length=8192 srcPos=87 dst.length=9 dstPos=0 length=-78
	at java.lang.System.arraycopy(System.java:292)
	at com.android.okhttp.okio.Buffer.read(Buffer.java:743)
	at com.android.okhttp.okio.Buffer.readFully(Buffer.java:731)
	at com.android.okhttp.okio.Buffer.readByteArray(Buffer.java:720)
	at com.android.okhttp.okio.Buffer.readByteArray(Buffer.java:707)
	at com.android.okhttp.internal.Platform.concatLengthPrefixed(Platform.java:137)
	at com.android.okhttp.internal.Platform.configureTlsExtensions(Platform.java:88)
	at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:99)
	at com.android.okhttp.Connection.connect(Connection.java:143)
	at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:185)
	at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
	at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:433)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:114)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:245)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:25)

**Comment by swankjesse** [comment]
The stacktrace is for Android’s bundled Okio: `com.android.okhttp.okio`. No action for us to take unfortunately.

**Comment by kaitian521** [comment]
met this again

**Comment by Keshava11** [comment]
I was getting this issue in one of the interceptor implementation where multiple parallel requests to refresh token were ending up in a crash.

I got it resolved by adding synchronized on the interceptor method to avoid multiple requests to run parallelly to refresh token whenever token expires.

Not sure if it's the case with all.

**Comment by Sabboo** [comment]
> I was getting this issue in one of the interceptor implementation where multiple parallel requests to refresh token were ending up in a crash.
> 
> I got it resolved by adding synchronized on the interceptor method to avoid multiple requests to run parallelly to refresh token whenever token expires.
> 
> Not sure if it's the case with all.

I can say that this what was causing the issue with me, after some tries it ends up to be an issue with headers manipulation.

If you are adding or removing headers from your requests, this might lead to posted stacktrace.

I ended up synchronising only the headers manipulation part to keep the parallel requests functionality working as expected.
