### ISSUE TITLE
Fatal Exception: java.lang.AssertionError

### ISSUE THREAD

**Issue by ashwini009** [square/okio#334]
```
Fatal Exception: java.lang.AssertionError
       at okio.AsyncTimeout.scheduleTimeout(AsyncTimeout.java:101)
       at okio.AsyncTimeout.enter(AsyncTimeout.java:80)
       at okio.AsyncTimeout$2.read(AsyncTimeout.java:235)
       at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345)
       at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:3217)
       at com.squareup.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
       at com.squareup.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
       at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
       at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:609)
       at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:460)
       at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:399)
       at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:527)
       at com.squareup.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
       at com.squareup.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25)
       at com.android.volley.toolbox.HurlStack.performRequest(HurlStack.java:107)
       at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:94)
       at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:111)
```

I have tried following the steps [Issue-3641]( https://github.com/square/okhttp/issues/3641). As @lucastsantos mentioned about disabling D8, I tried that but somehow the build was not getting generated giving this error: 
```
Error:com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/ashwinikumar/Documents/Projects/android/app/build/intermediates/transforms/desugar/qa/debug/132.jar
Error:com.android.builder.dexing.DexArchiveBuilderException: Error while dexing autovalue/shaded/com/google$/common/collect/$Multimaps.class
Error:com.android.dx.cf.code.SimException: default or static interface method used without --min-sdk-version >= 24
Error:Execution failed for task ':app:transformClassesWithDexBuilderForQaDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/ashwinikumar/Documents/Projects/android/app/build/intermediates/transforms/desugar/qa/debug/132.jar
Information:BUILD FAILED in 1m 30s
```

While looking out for this failure, I found that its coming because of D8 being disabled. Now, this becomes a dead loop for me. Also, following another suggestion in [Issue-3641]( https://github.com/square/okhttp/issues/3641), I tried to build the apk enabling D8 in Android Studio 3.1 Canary channel hoping that it was a D8 bug which is fixed and released the app and to add to the chaos, I can see the same crash on Crashlytics. Please help in fixing this issue as it is affecting many of our users.

**Comment by swankjesse** [comment]
Unsure what action we can take here. We might be able to change our code to avoid triggering bugs in some vendor’s VMs.
