### ISSUE TITLE
AssertionError on one Acer device

### ISSUE THREAD

**Issue by Tolriq** [square/okio#363]
Got this crash on an Acer device (A1-810) Android 4.4.2 (From Crashlytics so no more details)

I suppose this is a specific device error, but reporting in case not :)

Never saw that one before last update to okio but maybe coincidence and not related.

Is suppose catching the Assertion as a workaround would have unpredictable result seeing where it occurs ?

```
Fatal Exception: java.lang.AssertionError
       at okio.AsyncTimeout.scheduleTimeout(AsyncTimeout.java:101)
       at okio.AsyncTimeout.enter(AsyncTimeout.java:80)
       at okio.AsyncTimeout$2.read(AsyncTimeout.java:235)
       at okio.RealBufferedSource.read(RealBufferedSource.java:47)
       at okhttp3.internal.http1.Http1Codec$AbstractSource.read(Http1Codec.java:363)
       at okhttp3.internal.http1.Http1Codec$FixedLengthSource.read(Http1Codec.java:407)
       at okio.RealBufferedSource.indexOfElement(RealBufferedSource.java:3394)
       at com.squareup.moshi.JsonUtf8Reader.nextQuotedValue(JsonUtf8Reader.java:786)
       at com.squareup.moshi.JsonUtf8Reader.nextString(JsonUtf8Reader.java:591)
       at com.squareup.moshi.StandardJsonAdapters$10.fromJson(StandardJsonAdapters.java:2204)
       at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
       at com.squareup.moshi.MapJsonAdapter.fromJson(MapJsonAdapter.java:2069)
       at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
       at com.squareup.moshi.ClassJsonAdapter.com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:1205)
       at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
       at com.squareup.moshi.CollectionJsonAdapter.fromJson(CollectionJsonAdapter.java:76)
       at com.squareup.moshi.CollectionJsonAdapter$2.toJson(CollectionJsonAdapter.java:53)
       at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
       at com.squareup.moshi.ClassJsonAdapter.com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:1205)
       at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
       at com.squareup.moshi.ClassJsonAdapter.com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:1205)
       at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
       at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:35)
```

**Comment by Tolriq** [comment]
After more investigation it's a D8 error that should be fixed in AS 3.1 final.
