### ISSUE TITLE
java.net.SocketTimeoutException: timeout

### ISSUE THREAD

**Issue by louiewh** [square/okio#461]
okhttp-3.8.0, two-way ssl post large file to service
if large file > 200M, happen this, small file no this problem:

 at okio.Okio$3.newTimeoutException(Okio.java:210)
                                                                      at okio.AsyncTimeout.exit(AsyncTimeout.java:277)
                                                                      at okio.AsyncTimeout$2.read(AsyncTimeout.java:244)
                                                                      at okio.RealBufferedSource.indexOf(RealBufferedSource.java:325)
                                                                      at okio.RealBufferedSource.indexOf(RealBufferedSource.java:314)
                                                                      at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210)
                                                                      at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
                                                                      at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:75)
                                                                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.tools.profiler.support.network.okhttp.reflection.okhttp3.Interceptor$$Chain$.proceed(Interceptor$.java:52)
                                                                      at com.android.tools.profiler.support.network.okhttp.OkHttp3Interceptor.invoke(OkHttp3Interceptor.java:53)
                                                                      at java.lang.reflect.Proxy.invoke(Proxy.java:393)
                                                                      at $Proxy1.intercept(Unknown Source)
                                                                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                      at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
                                                                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                      at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
                                                                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                      at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                                                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                      at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
                                                                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                      at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
                                                                      at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
                                                                      at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                      at java.lang.Thread.run(Thread.java:818)

**Comment by dieyidezui** [comment]
Actually, you should set OkHttpClient.Builder.readTimeout() bigger.

**Comment by swankjesse** [comment]
This isn’t actionable. To reopen please provide an executable test case.
