### ISSUE TITLE
Please try this exception try catch, it will cause crash.

### ISSUE THREAD

**Issue by 43350860** [square/okio#512]
java.lang.AssertionError: java.io.EOFException
	at com.android.okhttp.okio.Buffer.clear(Buffer.java:764)
	at com.android.okhttp.okio.RealBufferedSource.close(RealBufferedSource.java:397)
	at com.android.okhttp.internal.framed.Http2$Reader.close(Http2.java:359)
	at com.android.okhttp.internal.Util.closeQuietly(Util.java:71)
	at com.android.okhttp.internal.framed.FramedConnection$Reader.execute(FramedConnection.java:618)
	at com.android.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.io.EOFException
	at com.android.okhttp.okio.Buffer.skip(Buffer.java:771)
	at com.android.okhttp.okio.Buffer.clear(Buffer.java:762)
	... 6 more

**Comment by swankjesse** [comment]
Which device is this? It’s my understanding that the com.android bundled OkHttp doesn’t enable HTTP/2.

**Comment by bubbleguuum** [comment]
I've seen this stack trace happening on Samsung devices running Android 11, orinating from MediaMetadataRetriever.release().
In the grand scheme of things, this exception is very rare and can be worked-around by catching AssertionError:

```
java.lang.AssertionError: java.io.EOFException
            at com.android.okhttp.okio.Buffer.clear(Buffer.java:766)
            at com.android.okhttp.okio.RealBufferedSource.close(RealBufferedSource.java:423)
            at com.android.okhttp.okio.RealBufferedSource$1.close(RealBufferedSource.java:410)
            at java.io.BufferedInputStream.close(BufferedInputStream.java:485)
            at android.media.MediaHTTPConnection.teardownConnection(MediaHTTPConnection.java:203)
            at android.media.MediaHTTPConnection.disconnect(MediaHTTPConnection.java:187)
            at android.media.IMediaHTTPConnection$Stub.onTransact(IMediaHTTPConnection.java:132)
            at android.os.Binder.execTransactInternal(Binder.java:1195)
            at android.os.Binder.execTransact(Binder.java:1159)
            at android.media.MediaMetadataRetriever.release(Native Method)
            ...
```

**Comment by swankjesse** [comment]
@bubbleguuum I see the package is com.android.okhttp, which means this is an old version of OkHttp that shipped in this particular device as its implementation of HttpURLConnection. That means there's nothing we can do here. You could probably avoid this problem by using OkHttp directly for this request.

**Comment by bubbleguuum** [comment]
Thank you for the response. I mention it mostly for info as this happens very rarely, and I worked-around it catching AssertionError around MediaMetadataRetriever.release().
