### ISSUE TITLE
AsyncTimeout AND Watchdog problem

### ISSUE THREAD

**Issue by hero-zhanghao** [square/okio#533]
HI，I used OKHTT3 in the project, version 3.8.1, and OKIO version 1.13.0.
In the process of running, I found a thread stuck. The thread stack is as follows:

> "pool-10-thread-1" #49 prio=5 os_prio=0 tid=0x00007f4b02a4f000 nid=0x3090 runnable [0x00007f4ad3f7b000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:211)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:75)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
	at okhttp3.RealCall.execute(RealCall.java:69)

OKHTTPClinent is created and used directly:

` private static OkHttpClient createOkHttpClient() {
        OkHttpClient.Builder builder = new OkHttpClient.Builder();
        return builder.build();
    }`

When I was looking for the problem, I found a timeout thread "Okio Watchdog" watching the connection, but I looked at the thread stack and got the following information:

> "Okio Watchdog" #17164 daemon prio=5 os_prio=0 tid=0x00007f4a10006800 nid=0x4ae8 in Object.wait() [0x00007f4ad0329000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:460)
	at okio.AsyncTimeout.awaitTimeout(AsyncTimeout.java:361)
	at okio.AsyncTimeout$Watchdog.run(AsyncTimeout.java:312)
	- locked <0x00000000c4e4fef8> (a java.lang.Class for okio.AsyncTimeout)

   Locked ownable synchronizers:
	- None

It seems that the "Okio Watchdog" thread has been waiting and has not been woken up. This state has lasted for 4 hours. Should I solve this problem?
THX

**Comment by swankjesse** [comment]
Can you reproduce this at all?

There’s two different mechanisms to trigger a timeout here; both the socket read timeout and the Okio timeout. Since neither is firing here I suspect it to be a problem bigger than Okio or OkHttp.

**Comment by hero-zhanghao** [comment]
It's a probability problem, and it takes long enough for the probability to show up.
There have been several times before, and the reset was resolved.
The project runs on the contos system.

**Comment by swankjesse** [comment]
Can you create a heap dump of a stuck system and post it online somewhere for me to investigate?
https://stackoverflow.com/a/3042463/40013

Note that heap dumps contain all of the data in your process so you should definitely not do this if your process contains secret or confidential data that you wouldn’t want public.

**Comment by hero-zhanghao** [comment]
Sorry, this is my problem, this thread is performing a timed task, in the task loop has to make HTTP requests.
There were so many requests, I think it got stuck in the request, but it wasn't. Four and a half hours later the mission ended.
Thank you very much for your reply. Please close this issses.
