### ISSUE TITLE
Infinite recursion

### ISSUE THREAD

**Issue by russgold** [square/okio#556]
We're seeing what appears to be an infinite recursion in the code, which winds up resulting in a memory condition. Here is the stack (with 2.2.0) from a thread dump before the exception is thrown is:

```
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
	- locked <0x00000000b165c670> (a java.lang.Object)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	- locked <0x00000000b165c740> (a sun.security.ssl.AppInputStream)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
	at okio.RealBufferedSource.request(RealBufferedSource.java:71)
	at okio.RealBufferedSource.require(RealBufferedSource.java:64)
	at okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:270)
	at com.squareup.okhttp.internal.http.Http1xStream$ChunkedSource.readChunkSize(Http1xStream.java:454)
	at com.squareup.okhttp.internal.http.Http1xStream$ChunkedSource.read(Http1xStream.java:435)
	at okio.RealBufferedSource.read(RealBufferedSource.java:50)
	at okio.ForwardingSource.read(ForwardingSource.java:35)
	at io.kubernetes.client.ProgressResponseBody$1.read(ProgressResponseBody.java:66)
	at okio.RealBufferedSource.read(RealBufferedSource.java:50)
	at okio.ForwardingSource.read(ForwardingSource.java:35)
	at io.kubernetes.client.ProgressResponseBody$1.read(ProgressResponseBody.java:66)
	at okio.RealBufferedSource.read(RealBufferedSource.java:50)
	at okio.ForwardingSource.read(ForwardingSource.java:35)
	at io.kubernetes.client.ProgressResponseBody$1.read(ProgressResponseBody.java:66)
	at okio.RealBufferedSource.read(RealBufferedSource.java:50)
	at okio.ForwardingSource.read(ForwardingSource.java:35)
	at io.kubernetes.client.ProgressResponseBody$1.read(ProgressResponseBody.java:66)
	at okio.RealBufferedSource.read(RealBufferedSource.java:50)
	at okio.ForwardingSource.read(ForwardingSource.java:35)
	at io.kubernetes.client.ProgressResponseBody$1.read(ProgressResponseBody.java:66)
	at okio.RealBufferedSource.read(RealBufferedSource.java:50)
	at okio.ForwardingSource.read(ForwardingSource.java:35)
	at io.kubernetes.client.ProgressResponseBody$1.read(ProgressResponseBody.java:66)
	at okio.RealBufferedSource.read(RealBufferedSource.java:50)
	at okio.ForwardingSource.read(ForwardingSource.java:35)
	at io.kubernetes.client.ProgressResponseBody$1.read(ProgressResponseBody.java:66)
	at okio.RealBufferedSource.read(RealBufferedSource.java:50)
	at okio.ForwardingSource.read(ForwardingSource.java:35)
	at io.kubernetes.client.ProgressResponseBody$1.read(ProgressResponseBody.java:66)
	at okio.RealBufferedSource.read(RealBufferedSource.java:50)
	at okio.ForwardingSource.read(ForwardingSource.java:35)
	at io.kubernetes.client.ProgressResponseBody$1.read(ProgressResponseBody.java:66)
	at okio.RealBufferedSource.read(RealBufferedSource.java:50)
	at okio.ForwardingSource.read(ForwardingSource.java:35)
	at io.kubernetes.client.ProgressResponseBody$1.read(ProgressResponseBody.java:66)
	at okio.RealBufferedSource.read(RealBufferedSource.java:50)
	at okio.ForwardingSource.read(ForwardingSource.java:35)
	at io.kubernetes.client.ProgressResponseBody$1.read(ProgressResponseBody.java:66)
	at okio.RealBufferedSource.read(RealBufferedSource.java:50)
	at okio.ForwardingSource.read(ForwardingSource.java:35)
	at io.kubernetes.client.ProgressResponseBody$1.read(ProgressResponseBody.java:66)
	at okio.RealBufferedSource.read(RealBufferedSource.java:50)
	at okio.ForwardingSource.read(ForwardingSource.java:35)
	at io.kubernetes.client.ProgressResponseBody$1.read(ProgressResponseBody.java:66)
	at okio.RealBufferedSource.read(RealBufferedSource.java:50)
	at okio.ForwardingSource.read(ForwardingSource.java:35)
	at io.kubernetes.client.ProgressResponseBody$1.read(ProgressResponseBody.java:66)
	at okio.RealBufferedSource.read(RealBufferedSource.java:50)
	at okio.ForwardingSource.read(ForwardingSource.java:35)
	at io.kubernetes.client.ProgressResponseBody$1.read(ProgressResponseBody.java:66)
```

**Comment by swankjesse** [comment]
Looks like a bug in `io.kubernetes.client.ProgressResponseBody` or how we call it. I think that's open source so it shouldn't be too hard to diagnose.

**Comment by swankjesse** [comment]
No action to take in Okio.
