### ISSUE TITLE
 java.lang.ClassCastException: okio.ByteString cannot be cast to java.lang.Comparable

### ISSUE THREAD

**Issue by austince** [square/okio#559]
When deploying to an Apache Flink 1.6 cluster on AWS EMR 5.18.0, okhttp throws an error with okio. Locally, everything runs smoothly (as they always say...).

```
Caused by: java.lang.ExceptionInInitializerError
	at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1313)
	at okhttp3.HttpUrl.get(HttpUrl.java:917)
	at okhttp3.Request$Builder.url(Request.java:165)
	... 9 more
Caused by: java.lang.ClassCastException: okio.ByteString cannot be cast to java.lang.Comparable
	at java.util.ComparableTimSort.countRunAndMakeAscending(ComparableTimSort.java:320)
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:188)
	at java.util.Arrays.sort(Arrays.java:1312)
	at java.util.Arrays.sort(Arrays.java:1506)
	at java.util.ArrayList.sort(ArrayList.java:1462)
	at java.util.Collections.sort(Collections.java:141)
	at kotlin.collections.CollectionsKt__MutableCollectionsJVMKt.sort(MutableCollectionsJVM.kt:27)
	at okio.Options$Companion.of(Options.kt:43)
	at okio.Options.of(Options.kt)
	at okhttp3.internal.Util.<clinit>(Util.java:73)
```

Dependency setup:
```xml
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>3.13.1</version>
        </dependency>

        <!-- Dependency of okhttp -->
        <dependency>
            <groupId>com.squareup.okio</groupId>
            <artifactId>okio</artifactId>
            <version>2.2.2</version>
        </dependency>
```

JVM:
```
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
```

EMR configured apps:
- Hadoop  2.8.4
- Flink 1.6.0
- Hue 4.2.0

I have seen other posts about conflicts with Apache Spark, but have not seen this error nor mentions of conflicts with Flink. If this is just a simple version conflict, how might I go about fixing it?

Thank you!

**Comment by JakeWharton** [comment]
Are you able to dump the classpath of the runtime? ByteString was made Comparable in 1.5.0 so if there's an earlier version prepended to the classpath it could be classloaded first.

**Comment by austince** [comment]
I think I have found the issue in the Flink uber jar:

```
jar -tf flink-shaded-hadoop2-uber-1.6.0.jar | grep okio
META-INF/maven/com.squareup.okio/
META-INF/maven/com.squareup.okio/okio/
META-INF/maven/com.squareup.okio/okio/pom.properties
META-INF/maven/com.squareup.okio/okio/pom.xml
okio/
okio/AsyncTimeout$1.class
okio/AsyncTimeout$2.class
okio/AsyncTimeout$Watchdog.class
okio/AsyncTimeout.class
okio/Base64.class
okio/Buffer$1.class
okio/Buffer$2.class
okio/Buffer.class
okio/BufferedSink.class
okio/BufferedSource.class
okio/ByteString.class
okio/DeflaterSink.class
okio/ForwardingSink.class
okio/ForwardingSource.class
okio/ForwardingTimeout.class
okio/GzipSink.class
okio/GzipSource.class
okio/InflaterSource.class
okio/Okio$1.class
okio/Okio$2.class
okio/Okio$3.class
okio/Okio.class
okio/RealBufferedSink$1.class
okio/RealBufferedSink.class
okio/RealBufferedSource$1.class
okio/RealBufferedSource.class
okio/Segment.class
okio/SegmentPool.class
okio/SegmentedByteString.class
okio/Sink.class
okio/Source.class
okio/Timeout$1.class
okio/Timeout.class
okio/Util.class
```

I know this isn't directly related to this lib, but do you know offhand how to specify using the packaged version and not the provided one?

**Comment by austince** [comment]
Should I just downgrade my library to use `1.4.0`?

**Comment by swankjesse** [comment]
You should tell flink to shade their dependencies in the uberjar. And update!

**Comment by austince** [comment]
Ok, thank you for your help!

**Comment by austince** [comment]
For anyone else who might find their way to this thread, here is [a convo with the mailing list about how to solve this issue](https://lists.apache.org/thread.html/%3CCALGL+UBoPsJiUE3UpZVqS-z1MmK0CyaSDkdrWkCxmC_CcsMr6w@mail.gmail.com%3E). And here is [the debugging classloading guide.](https://ci.apache.org/projects/flink/flink-docs-release-1.6/monitoring/debugging_classloading.html#overview-of-classloading-in-flink)
