### ISSUE TITLE
Weird NPE on Android Q Beta 2 only

### ISSUE THREAD

**Issue by bubbleguuum** [square/okio#591]
Seen in crash reports on Pixel devices running Q Beta 2.
Also see https://stackoverflow.com/questions/55520323/internal-crash-on-android-q for another report.

App is built with okio 1.15.0, but apparently it is the platform's okttp/okio that is used at runtime.

```
java.lang.NullPointerException: Attempt to read from field 'int com.android.okhttp.okio.Segment.limit' on a null object reference
at com.android.okhttp.okio.Buffer.write(Buffer.java:1184)
at com.android.okhttp.okio.Buffer.read(Buffer.java:1223)
at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:56)
at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:395)
at com.android.okhttp.internal.Util.skipAll(Util.java:165)
at com.android.okhttp.internal.Util.discard(Util.java:147)
at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.close(Http1xStream.java:412)
at com.android.okhttp.okio.RealBufferedSource.close(RealBufferedSource.java:397)
at com.android.okhttp.okio.RealBufferedSource$1.close(RealBufferedSource.java:385)
at java.io.BufferedInputStream.close(BufferedInputStream.java:485)
at android.media.MediaHTTPConnection.teardownConnection(MediaHTTPConnection.java:161)
at android.media.MediaHTTPConnection.access$000(MediaHTTPConnection.java:43)
at android.media.MediaHTTPConnection$1.run(MediaHTTPConnection.java:149)
```

**Comment by swankjesse** [comment]
This is the old bundled Okio that comes with Android.

Do you access any streams from multiple threads concurrently? Perhaps calling close() from one thread when another thread is reading?

**Comment by bubbleguuum** [comment]
My app uses an old version of Glide (3 years old now I think) using okhttp 2.7.5 (thus okio 1.X).
This is for loading images in ListView (yup, good old ListView). I did not upgrade Glide because it has been working flawlessly. Until these crashes that only happens on Q beta 2. I wonder if this is not Q putting in light a possible bug in Glide due to different thread scheduling and timings...
In any case, I'm not the only one affected judging by the SO post I linked to.

**Comment by bubbleguuum** [comment]
Oh, not sure how I could miss it but the stack trace comes from android.media.MediaHTTPConnection. So it has nothing to do with Glide. My app do http streaming so the bug seems to be in Q from this internal framework class (MediaHTTPConnection) that probably uses okio/ohttp improperly. So I will report this on the Amdroid Q bugtracker.

**Comment by bubbleguuum** [comment]
Here it is: https://issuetracker.google.com/issues/130410728

**Comment by swankjesse** [comment]
No action for Okio to take on this.

**Comment by Mercandj** [comment]
Good to know that it will be fixed [here](https://android-review.googlesource.com/c/platform/frameworks/base/+/938639/), thanks!

(reproduced on Q beta 2 on pixel with `com.squareup.okhttp:okhttp:2.5.0`)
