### ISSUE TITLE
Okio 1.17.4 ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by liuyanqiang1** [square/okio#645]
Okio 1.17.4
okhttp 3.12.3
java.lang.ArrayIndexOutOfBoundsException: 8193
	at okio.Buffer.writeUtf8(Buffer.java:986)
	at okio.Buffer.writeUtf8(Buffer.java:961)
	at okio.RealBufferedSink.writeUtf8(RealBufferedSink.java:53)
	at okhttp3.internal.http1.Http1Codec.writeRequest(Http1Codec.java:172)
	at okhttp3.internal.connection.RealConnection.createTunnel(RealConnection.java:382)
	at okhttp3.internal.connection.RealConnection.connectTunnel(RealConnection.java:220)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:161)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:258)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at com.kuaishou.framework.http.OkHttp3RejectedExecutionHandler.intercept(OkHttp3RejectedExecutionHandler.java:69)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at com.kuaishou.framework.http.ForceHostInterceptor3.intercept(ForceHostInterceptor3.java:36)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:250)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:201)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by swankjesse** [comment]
I investigated this this morning and wasn’t able to see a path that’d cause this exception. The relevant code is `writableSegment()`

```
  Segment writableSegment(int minimumCapacity) {
    if (minimumCapacity < 1 || minimumCapacity > Segment.SIZE) throw new IllegalArgumentException();

    if (head == null) {
      head = SegmentPool.take(); // Acquire a first segment.
      return head.next = head.prev = head;
    }

    Segment tail = head.prev;
    if (tail.limit + minimumCapacity > Segment.SIZE || !tail.owner) {
      tail = tail.push(SegmentPool.take()); // Append a new empty segment to fill up.
    }
    return tail;
  }
```

and this fragment of writeUtf8(), which is where we fail.
```
        Segment tail = writableSegment(1);
        byte[] data = tail.data;
        int segmentOffset = tail.limit - i;
        int runLimit = Math.min(endIndex, Segment.SIZE - segmentOffset);

        // Emit a 7-bit character with 1 byte.
        data[segmentOffset + i++] = (byte) c; // EXCEPTION HERE
```

From the writableSegment(1) result, we can deduce `tail.limit < 8192`, which is to say that `tail.limit` is at most 8191.

The index into the array on the line we crash is `segmentOffset + i`, which is `tail.limit - i + i`, which is `tail.limit`, which is at most 8191.

My conclusion is that there’s something else in your program manipulating `tail.limit`, likely a concurrent access. Likely what’s happening is elsewhere on your system there’s a thread that’s polluting the segment pool with invalid segments. 

This is Very Problematic! And I think we should consider adding defenses to Okio to detect such invalid accesses and crash the program with a more useful error when they occur.
