### ISSUE TITLE
ArrayIndexOutOfBoundsException in ArrayUtils.checkOffsetAndCount

### ISSUE THREAD

**Issue by Jeff11** [square/okio#675]
After updating to okio 2.4.1 we got reports for this crash from Android 9 devices:

```
java.lang.ArrayIndexOutOfBoundsException: 
  at com.android.org.conscrypt.ArrayUtils.checkOffsetAndCount (ArrayUtils.java:31)
  at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read (ConscryptFileDescriptorSocket.java:563)
  at okio.InputStreamSource.read (InputStreamSource.java:93)
  at okio.AsyncTimeout$source$1.read (AsyncTimeout.java:129)
  at okio.RealBufferedSource.read (RealBufferedSource.java:188)
  at okhttp3.internal.http2.Http2Stream$FramingSource.receive$okhttp (Http2Stream.java:441)
  at okhttp3.internal.http2.Http2Stream.receiveData (Http2Stream.java:272)
  at okhttp3.internal.http2.Http2Connection$ReaderRunnable.data (Http2Connection.java:599)
  at okhttp3.internal.http2.Http2Reader.readData (Http2Reader.java:178)
  at okhttp3.internal.http2.Http2Reader.nextFrame (Http2Reader.java:117)
  at okhttp3.internal.http2.Http2Connection$ReaderRunnable.run (Http2Connection.java:567)
  at java.lang.Thread.run (Thread.java:764)
```

**Comment by Vuthe** [comment]
> After updating to okio 2.4.1 we got reports for this crash from Android 9 devices:
> 
> ```
> java.lang.ArrayIndexOutOfBoundsException: 
>   at com.android.org.conscrypt.ArrayUtils.checkOffsetAndCount (ArrayUtils.java:31)
>   at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read (ConscryptFileDescriptorSocket.java:563)
>   at okio.InputStreamSource.read (InputStreamSource.java:93)
>   at okio.AsyncTimeout$source$1.read (AsyncTimeout.java:129)
>   at okio.RealBufferedSource.read (RealBufferedSource.java:188)
>   at okhttp3.internal.http2.Http2Stream$FramingSource.receive$okhttp (Http2Stream.java:441)
>   at okhttp3.internal.http2.Http2Stream.receiveData (Http2Stream.java:272)
>   at okhttp3.internal.http2.Http2Connection$ReaderRunnable.data (Http2Connection.java:599)
>   at okhttp3.internal.http2.Http2Reader.readData (Http2Reader.java:178)
>   at okhttp3.internal.http2.Http2Reader.nextFrame (Http2Reader.java:117)
>   at okhttp3.internal.http2.Http2Connection$ReaderRunnable.run (Http2Connection.java:567)
>   at java.lang.Thread.run (Thread.java:764)
> ```

**Comment by Jeff11** [comment]
I have not seen this crash in newer builds with updated Android Gradle plugin anymore.

**Comment by anonrootkit** [comment]
Issue still persists, kindly check and do the needful. Find the stacktrace below : 

``` 
java.lang.ArrayIndexOutOfBoundsException: size=50 offset=0 byteCount=7504
    at okio.-Util.checkOffsetAndCount
    at okio.AsyncTimeout$sink$1.write(AsyncTimeout.kt:85)
    at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255)
    at okio.RealBufferedSink.writeUtf8(RealBufferedSink.kt:162)
    at okhttp3.internal.http1.Http1ExchangeCodec.writeRequest(Http1ExchangeCodec.kt:161)
    at okhttp3.internal.http1.Http1ExchangeCodec.writeRequestHeaders(Http1ExchangeCodec.kt:119)
    at okhttp3.internal.connection.Exchange.writeRequestHeaders
    at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:36)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at com.baja.app.data.network.config.APIService$httpClient$lambda-1$$inlined$-addNetworkInterceptor$1.intercept(OkHttpClient.kt:1081)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at com.baja.app.data.network.config.APIService$getOkHttpClient$$inlined$-addInterceptor$1.intercept(OkHttpClient.kt:1092)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at com.baja.app.data.network.config.TimeoutInterceptor.intercept(TimeoutInterceptor.kt:32)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
    at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:919)
```
