### ISSUE TITLE
Attempt to read from field 'int com.android.okhttp.okio.Segment.limit' on a null object reference

### ISSUE THREAD

**Issue by judemanutd** [square/okio#683]
Getting alot of these logged in the firebase crashlytics console. Posting the log straight from the firebase console. I do send an image in the notification for users which is handled internally by the system and displayed so I don't have any special code for downloading images and displaying it in the notification. Could that have something to do with this? 

https://firebase.google.com/docs/cloud-messaging/android/send-image

```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'int com.android.okhttp.okio.Segment.limit' on a null object reference
       at com.android.okhttp.okio.Buffer.write(Buffer.java:1182)
       at com.android.okhttp.okio.Buffer.read(Buffer.java:1221)
       at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:65)
       at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:602)
       at com.android.okhttp.internal.Util.skipAll(Util.java:172)
       at com.android.okhttp.internal.Util.discard(Util.java:154)
       at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.close(Http1xStream.java:619)
       at com.android.okhttp.okio.RealBufferedSource.close(RealBufferedSource.java:421)
       at com.android.okhttp.okio.RealBufferedSource$1.close(RealBufferedSource.java:409)
       at com.google.android.gms.internal.firebase_messaging.zzk.zza(com.google.firebase:firebase-messaging@@20.0.1:4)
       at com.google.firebase.messaging.zzj.close(com.google.firebase:firebase-messaging@@20.0.1:37)
       at com.google.firebase.messaging.zzd.zza(com.google.firebase:firebase-messaging@@20.0.1:51)
       at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.0.1:60)
       at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.0.1:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.android.gms.common.util.concurrent.zza.run(:6)
       at java.lang.Thread.run(Thread.java:764)
```

**Comment by swankjesse** [comment]
Typically this indicates unsafe concurrent access to Okio streams. You should report upstream to the Firebase team.
