### ISSUE TITLE
Proguard issue

### ISSUE THREAD

**Issue by morder** [square/okio#684]
Proguarded version cause this error
```
Fatal Exception: javax.net.ssl.SSLException: Read error: ssl=0xea3c5c60: I/O error during system call, Software caused connection abort
       at com.android.org.conscrypt.NativeCrypto.SSL_read(NativeCrypto.java)
       at com.android.org.conscrypt.SslWrapper.read(SslWrapper.java:391)
       at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:567)
       at okio.Okio$2.read(Okio.java:140)
       at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
       at okio.RealBufferedSource.request(RealBufferedSource.java:72)
       at okio.RealBufferedSource.require(RealBufferedSource.java:65)
       at okhttp3.internal.http2.Http2Reader.nextFrame(Http2Reader.java:96)
       at okhttp3.internal.http2.Http2Connection$ReaderRunnable.execute(Http2Connection.java:600)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.lang.Thread.run(Thread.java:764)
```

With the rule `-keep class okio.**` everything is ok

This crash is reproduced when you start loading some big data from `https` host and quickly turning off wi-fi

**Comment by swankjesse** [comment]
That exception appears to be caused by a network disconnect. I don’t think there’s any action to take here.
