### ISSUE TITLE
IllegalArgumentException at squareup.okio 

### ISSUE THREAD

**Issue by abhiCITI1** [square/okio#692]
Facing this exception while reading a message byte coming only for a particular server host

stacktrace : 
```
java.lang.IllegalArgumentException: byteCount < 0: -1
at okio.RealBufferedSource.request(RealBufferedSource.java:65)
at okio.RealBufferedSource.require(RealBufferedSource.java:61)
at okio.RealBufferedSource.readUtf8(RealBufferedSource.java:192)
```

okio version - 1.15.0

A quick response would be appreciated.
Thanks

**Comment by swankjesse** [comment]
Unfortunately this stacktrace isn’t enough to diagnose the problem. It looks like you’re requesting to read a string of length -1 bytes.
