### ISSUE TITLE
java.net.SocketException: socket is closed is seen with latest okio/okhttp4 library

### ISSUE THREAD

**Issue by anuj-dialpad** [square/okio#702]
Hi Thank you for the great library and the amazing work you guys do .
We are trying to upgrade our app to use latest okio(2.4.3)  and okhttp(4.4.0) library.
But we are seeing this weird issue of socket closed exception intermittently. This is causing issue as we show error message to user on any exception.

 ```
2020-02-28 16:43:50.282 7349-9218/co.switchapp W/System.err: java.net.SocketException: socket is closed
2020-02-28 16:43:50.283 7349-9218/co.switchapp W/System.err:     at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:588)
2020-02-28 16:43:50.283 7349-9218/co.switchapp W/System.err:     at okio.InputStreamSource.read(Okio.kt:93)
2020-02-28 16:43:50.283 7349-9218/co.switchapp W/System.err:     at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:129)
2020-02-28 16:43:50.283 7349-9218/co.switchapp W/System.err:     at okio.RealBufferedSource.request(RealBufferedSource.kt:207)
2020-02-28 16:43:50.283 7349-9218/co.switchapp W/System.err:     at okio.RealBufferedSource.require(RealBufferedSource.kt:201)
2020-02-28 16:43:50.283 7349-9218/co.switchapp W/System.err:     at okhttp3.internal.http2.Http2Reader.nextFrame(Http2Reader.kt:88)
2020-02-28 16:43:50.283 7349-9218/co.switchapp W/System.err:     at okhttp3.internal.http2.Http2Connection$ReaderRunnable.run(Http2Connection.kt:615)
2020-02-28 16:43:50.283 7349-9218/co.switchapp W/System.err:     at java.lang.Thread.run(Thread.java:919)
```

 This issue was already raised at https://github.com/square/okhttp/issues/4875#issuecomment-525132628
with okhttp  4.1.0.
FYI. Retrofit version is 2.7.2. 

Hopefully this information and the stack trace above is enough to be helpful, apologies for not being able to include a reproducible case outside of production

**Comment by swankjesse** [comment]
Looks like a normal close, caused either by the server, a cancel, or a timeout.

**Comment by anuj-dialpad** [comment]
No. I think this is an issue. It only happens when I upgrade to latest library. Works fine with older one.I get 200 from server as mentioned by Matt in linked issue. but as you can see this result into  exception.

**Comment by anuj-dialpad** [comment]
Hi Okio Team,
 I know you guys might be busy but can you guys check this once and let us know what we can do here? We are not able to upgrade due this issue with latest version.

**Comment by swankjesse** [comment]
@anuj-dialpad can you paste the server URL into SSL labs and report back it's SSL version and cipher suites?

https://www.ssllabs.com/ssltest/

**Comment by anuj-dialpad** [comment]
<img width="1046" alt="Screenshot 2020-03-12 at 11 26 09 AM" src="https://user-images.githubusercontent.com/52416735/76491671-4cfe8300-6454-11ea-8947-f8b0ac62f9d9.png">
Hi @swankjesse  please find the attached screenshot with the details you asked. Our server url is  https://dialpad.com/ .

**Comment by anuj-dialpad** [comment]
Hi @swankjesse , Let me know if you had any chance to look into this and if there is any update.

**Comment by swankjesse** [comment]
Try StackOverflow? Here in GitHub we only really want failing tests with test cases.

**Comment by SmallJia** [comment]
Dear anuj-dialpad
I have the same problem as you, and I can't upgrade to latest version due to this issue.
Excuse me, how did you solve this problem?

**Comment by leofirespotter** [comment]
> Dear anuj-dialpad
> I have the same problem as you, and I can't upgrade to latest version due to this issue.
> Excuse me, how did you solve this problem?

@SmallJia unfortunately we haven't yet. Sorry nothing to report.
