### ISSUE TITLE
In version 1.17.4, there are many lock waits

### ISSUE THREAD

**Issue by goodcode-best** [square/okio#744]
In version 1.17.4, there are many lock waits，the stack as follows:
"BlockDataReaderExecutor-97" #1238 daemon prio=5 os_prio=0 tid=0x0000fff4ec003000 nid=0x18f78 waiting for monitor entry [0x0000fff0d05fd000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at okio.AsyncTimeout.scheduleTimeout(AsyncTimeout.java:86)
	- waiting to lock <0x00000005213ab700> (a java.lang.Class for okio.AsyncTimeout)
	at okio.AsyncTimeout.enter(AsyncTimeout.java:80)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:235)
	at okio.RealBufferedSource.read(RealBufferedSource.java:47)
	at obs.shaded.okhttp3.internal.http1.Http1Codec$AbstractSource.read(Http1Codec.java:363)
	at obs.shaded.okhttp3.internal.http1.Http1Codec$FixedLengthSource.read(Http1Codec.java:407)
	at okio.RealBufferedSource$1.read(RealBufferedSource.java:440)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	- locked <0x00000003c12c4c38> (a java.io.BufferedInputStream)
	at org.apache.hadoop.fs.obs.OBSInputStream.read(OBSInputStream.java:436)
	- locked <0x00000003e6664980> (a org.apache.hadoop.fs.obs.OBSInputStream)
	at java.io.DataInputStream.read(DataInputStream.java:149)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at io.netty.buffer.UnsafeByteBufUtil.setBytes(UnsafeByteBufUtil.java:454)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:278)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1115)
	at alluxio.worker.block.UnderFileSystemBlockReader.transferTo(UnderFileSystemBlockReader.java:223)
	at alluxio.worker.grpc.BlockReadHandler$BlockDataReader.getDataBuffer(BlockReadHandler.java:110)
	at alluxio.worker.grpc.BlockReadHandler$BlockDataReader.getDataBuffer(BlockReadHandler.java:70)
	at alluxio.worker.grpc.AbstractReadHandler$DataReader.runInternal(AbstractReadHandler.java:325)
	at alluxio.worker.grpc.AbstractReadHandler$DataReader.run(AbstractReadHandler.java:293)
	at alluxio.worker.grpc.BlockReadHandler$BlockDataReader.run(BlockReadHandler.java:70)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at alluxio.worker.grpc.GrpcExecutors$ImpersonateThreadPoolExecutor.lambda$execute$0(GrpcExecutors.java:82)
	at alluxio.worker.grpc.GrpcExecutors$ImpersonateThreadPoolExecutor$$Lambda$87/1597811960.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by RichurLiu** [comment]
In version 1.17.2, I had a similar problem:
"log-monitor-thread-32153679128900-0" Id=128901 RUNNABLE
at okio.AsyncTimeout.cancelScheduledTimeout(AsyncTimeout.java:128)
- locked java.lang.Class@7e359aba
at okio.AsyncTimeout.exit(AsyncTimeout.java:122)
at okio.AsyncTimeout.exit(AsyncTimeout.java:275)
at okio.AsyncTimeout$1.write(AsyncTimeout.java:186)
at okio.RealBufferedSink.flush(RealBufferedSink.java:224)
at okhttp3.internal.http1.Http1ExchangeCodec.finishRequest(Http1ExchangeCodec.java:190)
at okhttp3.internal.connection.Exchange.finishRequest(Exchange.java:101)
at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:86)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
at com.github.dockerjava.okhttp.HijackingInterceptor.intercept(HijackingInterceptor.java:20)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:221)
at okhttp3.RealCall.execute(RealCall.java:81)
at com.github.dockerjava.okhttp.OkDockerHttpClient$OkResponse.(OkDockerHttpClient.java:256)
at com.github.dockerjava.okhttp.OkDockerHttpClient.execute(OkDockerHttpClient.java:230)
at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:228)
at com.github.dockerjava.core.DefaultInvocationBuilder.get(DefaultInvocationBuilder.java:202)
at com.github.dockerjava.core.DefaultInvocationBuilder.get(DefaultInvocationBuilder.java:74)
at com.github.dockerjava.core.exec.InspectContainerCmdExec.execute(InspectContainerCmdExec.java:31)
at com.github.dockerjava.core.exec.InspectContainerCmdExec.execute(InspectContainerCmdExec.java:13)
...
Number of locked synchronizers = 1
- java.util.concurrent.ThreadPoolExecutor$Worker@6b8bc1d5

**Comment by swankjesse** [comment]
Try  2.10.0 or newer? It fixes this problem for very highly contentious uses.

**Comment by RichurLiu** [comment]
Thank you for your reply. I still have some questions. How compatible is it with the new version(2.10.0 or newer)? What is the specific version(commit) of the fix? What is the root cause?

**Comment by swankjesse** [comment]
It’s very compatible. Details here.
https://square.github.io/okio/changelog/
