### ISSUE TITLE
NullPointerException in okio.InflaterSource.refill

### ISSUE THREAD

**Issue by hameno** [square/okio#786]
We're getting a NPE when upgrading from OkIo 1.14.0 to 2.9.0 in our xar library (https://github.com/sprylab/xar)
Branch: https://github.com/sprylab/xar/tree/update_okio

```
java.lang.NullPointerException
	at okio.InflaterSource.refill(InflaterSource.kt:115)
	at okio.InflaterSource.readOrInflate(InflaterSource.kt:76)
	at okio.InflaterSource.read(InflaterSource.kt:49)
	at okio.Buffer.writeAll(Buffer.kt:1642)
	at okio.RealBufferedSource.readByteArray(RealBufferedSource.kt:236)
	at com.sprylab.xar.XarEntry.getBytes(XarEntry.java:315)
	at com.sprylab.xar.writer.XarSinkTest.assertThatEntryEqualsFile(XarSinkTest.java:118)
	at com.sprylab.xar.writer.XarSinkTest.testAddCompressedAndHashedFileSourceToRoot(XarSinkTest.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)

```

The exception can be reproduced by running the test XarSinkTest#testAddCompressedAndHashedFileSourceToRoot

The usage is basically as following:
```java
Okio.buffer(new InflaterSource(Okio.buffer(new RandomAccessFileSource(file, offset, length)), new Inflater())).readByteArray()
```

file is 400 bytes
offset is 388
length is 12
original inflated content is only 4 bytes, deflated is 12 bytes

I tried finding the error but have been unsuccessful so far.

**Comment by swankjesse** [comment]
Looks like a Buffer’s invariants have been broken, probably either our bug or a race condition. We're trying to read a buffer with size > 0 but no segments.
```
    if (source.exhausted()) return true

    // Assign buffer bytes to the inflater.
    val head = source.buffer.head!! // NPE here
```

**Comment by hameno** [comment]
Yeah, that's how far I came aswell while debugging. Didn't enough of the logic there to proceed further...

**Comment by cketti** [comment]
Looks like `InflaterSource` never actually requests data from its `BufferedSource`. It just expects data to be in the `Buffer`.

**Comment by cketti** [comment]
@hameno: This is caused by a bug in your [`RandomAccessFileSource`](https://github.com/sprylab/xar/blob/6fd3bd6a2efc0169909a57952da026880bb9a621/xar/src/main/java/com/sprylab/xar/utils/RandomAccessFileSource.java#L61-L84). In the `read()` method you need to return `-1` if `remainingLength` is 0.

**Comment by hameno** [comment]
@cketti Thanks for digging into it. I'll test it once I have a bit more time and update this issue.

**Comment by hameno** [comment]
Adding the check does indeed fix the issues, thanks 👍
