### ISSUE TITLE
kotlin.KotlinNullPointerException

### ISSUE THREAD

**Issue by wangchao0837** [square/okio#875]
E/CrashHandler: In thread: Thread[OkHttp Dispatcher,5,main]
    UncaughtException detected: kotlin.KotlinNullPointerException
        at okio.Buffer.getByte(Buffer.kt:2224)
        at okio.Buffer.readUtf8Line$jvm(Buffer.kt:718)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:223)
        at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215)
        at okhttp3.internal.http1.Http1Codec.readHeaders(Http1Codec.java:224)
        at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:195)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.gstudentlib.SDKConfig$with$1.interceptor(SDKConfig.kt:127)
        at com.gsbaselib.net.interceptor.GatewayInterceptor.intercept(GatewayInterceptor.kt:14)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
        at okhttp3.RealCall.execute(RealCall.java:92)
        at com.gaosi.download.tools.HttpUtils.getContentLength(HttpUtils.java:23)
        at com.gaosi.download.process.CacheStratefyInterceptor.intercept(CacheStratefyInterceptor.java:41)
        at com.gaosi.download.RealProcessDispatcher.proceed(RealProcessDispatcher.java:54)
        at com.gaosi.download.process.FileManagerInterceptor.intercept(FileManagerInterceptor.java:32)
        at com.gaosi.download.RealProcessDispatcher.proceed(RealProcessDispatcher.java:54)
        at com.gaosi.download.RealTask$AsyncTask.getPostCardWithInterceptorChain(RealTask.java:159)
        at com.gaosi.download.RealTask$AsyncTask.execute(RealTask.java:113)
        at com.gaosi.download.DownloadRunnable.run(DownloadRunnable.java:21)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

**Comment by swankjesse** [comment]
Unclear what action to take on this. It looks like a possible race condition?

If you can create an executable test case to reproduce this, please do! And open another issue and we’ll fix promptly.
