### ISSUE TITLE
Cannot download a file

### ISSUE THREAD

**Issue by sergylopez21** [square/okio#937]
The response is a zip file. This is working fine because I can download the file with postman without issues.

I have implemented  this:

```
File downloadedFile = new File(Environment.getExternalStoragePublicDirectory(
                Environment.DIRECTORY_DOCUMENTS), "test.zip");
        BufferedSink sink = Okio.buffer(Okio.sink(downloadedFile));
        sink.writeAll(response.body().source());
        sink.close();
```
The post is working flawless, but the response is totally broken.I have the next error:
```

java.lang.IllegalStateException: closed
        at okio.RealBufferedSource.read(RealBufferedSource.kt:185)
        at okio.RealBufferedSink.writeAll(RealBufferedSink.kt:190)
        at com.example.a3dmap.map.getRectangle(map.java:284)
        at com.example.a3dmap.map$2.onClick(map.java:214)
        at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:177)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7562)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```
The error seems be in response.body().source(), maybe because the buffer is closed before time.

I just want to download the zip.

**Comment by swankjesse** [comment]
Executable test case please.

**Comment by sergylopez21** [comment]
class Post: 
```
package com.example.a3dmap;

import org.osmdroid.util.GeoPoint;

import java.io.IOException;
import java.util.ArrayList;

import okhttp3.MediaType;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;

public class Post {
    public static final MediaType JSON = MediaType.get("application/json; charset=utf-8");

    OkHttpClient client = new OkHttpClient.Builder().build();

    Response post(String url, String json) throws IOException {
        RequestBody body = RequestBody.create(json, JSON);
        Request request = new Request.Builder()
                .url(url)
                .post(body)
                .build();
        try (Response response = client.newCall(request).execute()) {
            return response;
        }
    }

    String createJSON(String name ,ArrayList<GeoPoint> polygon, ArrayList<GeoPoint> rectangle) {
        ArrayList<Double> cLat = new ArrayList<>();
        ArrayList<Double> cLong = new ArrayList<>();
        ArrayList<Double> rLat = new ArrayList<>();
        ArrayList<Double> rLong = new ArrayList<>();

        for (GeoPoint point : polygon) {
            cLat.add(point.getLatitude());
            cLong.add(point.getLongitude());
        }

        for (GeoPoint point : rectangle) {
            rLat.add(point.getLatitude());
            rLong.add(point.getLongitude());
        }

        return "{'name':'" + name +"',"
                + "'coords':"
                + "{'lat':" + cLat + ", 'long':" + cLong + "}"
                + ","
                + "'rectangle':"
                + "{'lat':" + rLat + ", 'long':" + rLong + "}"
                + "}";
    }
}
```

Android code:
```
@RequiresApi(api = Build.VERSION_CODES.KITKAT)
public void test() throws IOException{
Post post = new Post();
        // name,points,rectangle are varibles not relevant
        String json = post.createJSON(name,points,rectangle);
        String url = "https://osm2obj.herokuapp.com/test";

        Response response = null;

        try {
            int SDK_INT = android.os.Build.VERSION.SDK_INT;
            if (SDK_INT > 8)
            {
                StrictMode.ThreadPolicy policy = new StrictMode.ThreadPolicy.Builder()
                        .permitAll().build();
                StrictMode.setThreadPolicy(policy);
                response = post.post(url,json);


            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        File downloadedFile = new File(Environment.getExternalStoragePublicDirectory(
                Environment.DIRECTORY_DOCUMENTS), "kkk.zip");
        BufferedSink sink = Okio.buffer(Okio.sink(downloadedFile));
        sink.writeAll(response.body().source());
        sink.close();

        return null;
}
```
this code is implemented to send a json in the request, but it is irrelevant for the test case. I have implemented the response in [https://osm2obj.herokuapp.com/test](https://osm2obj.herokuapp.com/test), the POST request returns a zip file directly.

**Comment by swankjesse** [comment]
Can you make an isolated test case? Something that doesn't need any external dependencies or Android? There's an example here:
https://gist.github.com/swankjesse/981fcae102f513eb13ed

**Comment by sergylopez21** [comment]
```
import okhttp3.Call;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.MediaType;
import okhttp3.mockwebserver.MockResponse;
import okhttp3.mockwebserver.MockWebServer;
import okhttp3.mockwebserver.RecordedRequest;
import org.junit.Rule;
import org.junit.Test;

import static org.junit.Assert.assertEquals;

public class OkHttpBug {
  public static final MediaType JSON = MediaType.get("application/json; charset=utf-8");
  OkHttpClient client = new OkHttpClient.Builder().build();
  String json = post.createJSON("name",1,1,1,1);
  String url = "https://osm2obj.herokuapp.com/test";

  Response response = null;
  try {
            int SDK_INT = android.os.Build.VERSION.SDK_INT;
            if (SDK_INT > 8)
            {
                StrictMode.ThreadPolicy policy = new StrictMode.ThreadPolicy.Builder()
                        .permitAll().build();
                StrictMode.setThreadPolicy(policy);
                response = post.post(url,json);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        File downloadedFile = new File(Environment.getExternalStoragePublicDirectory(
                Environment.DIRECTORY_DOCUMENTS), "kkk.zip");
        BufferedSink sink = Okio.buffer(Okio.sink(downloadedFile));
        sink.writeAll(response.body().source());
        sink.close();

  String createJSON(String name , int cLat, int cLong, int rLat, int rLong, ) {
    
    return "{'name':'" + name +"',"
                + "'coords':"
                + "{'lat':" + cLat + ", 'long':" + cLong + "}"
                + ","
                + "'rectangle':"
                + "{'lat':" + rLat + ", 'long':" + rLong + "}"
                + "}";
  }

  Response post(String url, String json) throws IOException {
        RequestBody body = RequestBody.create(json, JSON);
        Request request = new Request.Builder()
                .url(url)
                .post(body)
                .build();
        try (Response response = client.newCall(request).execute()) {
            return response;
        }
    }

}
```

this should work without problems and without dependencies, sorry if it is not with test, because I honestly don't know if it would implement them well. The json should not give any problem because from the server side it receives it perfectly.

**Comment by sergylopez21** [comment]
In case someone else doesn't get it either, I have managed to download the file without problems using the following function:

```
writeResponseBodyToDisk(response.body());

@RequiresApi(api = Build.VERSION_CODES.KITKAT)
    private boolean writeResponseBodyToDisk(ResponseBody body) {
        try {
            // todo change the file location/name according to your needs
            File futureStudioIconFile = new File(Environment.getExternalStoragePublicDirectory(
                    Environment.DIRECTORY_DOCUMENTS),"name.zip");

            InputStream inputStream = null;
            OutputStream outputStream = null;

            try {
                byte[] fileReader = new byte[4096];

                long fileSize = body.contentLength();
                long fileSizeDownloaded = 0;

                inputStream = body.byteStream();
                outputStream = new FileOutputStream(futureStudioIconFile);

                while (true) {
                    int read = inputStream.read(fileReader);

                    if (read == -1) {
                        break;
                    }

                    outputStream.write(fileReader, 0, read);

                    fileSizeDownloaded += read;

                    Log.d("info", "file download: " + fileSizeDownloaded + " of " + fileSize);
                }

                outputStream.flush();

                return true;
            } catch (IOException e) {
                return false;
            } finally {
                if (inputStream != null) {
                    inputStream.close();
                }

                if (outputStream != null) {
                    outputStream.close();
                }
            }
        } catch (IOException e) {
            return false;
        }
    }
```

**Comment by JakeWharton** [comment]
The problem is your use of try-with-resources before returning the response. This will close the response object before returning the value and make the body unavailable. Remove the try-with-resources and force the consumer to do it.
